# Generated by Django 3.0 on 2020-02-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
