# Generated by Django 3.0 on 2020-04-04 05:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20200330_0016'),
        ('event', '0019_auto_20200404_0541'),
        ('plan', '0009_auto_20200402_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userplan',
            name='updated_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user_auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='user_auth.UserAuthModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user_event',
            field=models.ForeignKey(default=1, help_text='event of this plan', on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='event.UserEvent'),
            preserve_default=False,
        ),
    ]
