# Generated by Django 3.0 on 2020-10-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_auto_20200405_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='plan_code',
            field=models.UUIDField(editable=False, help_text='Unique plan code for each plan', null=True),
        ),
    ]
