# Generated by Django 3.0 on 2021-06-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_auto_20210508_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
    ]
