# Generated by Django 3.0 on 2021-07-07 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_subpackage_week_zone_focuses'),
        ('user_auth', '0023_remove_userauthmodel_user_id'),
        ('event', '0045_merge_20210629_0538'),
        ('plan', '0014_userplan_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='user_package',
            field=models.ForeignKey(help_text='Package for this plan', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_packages', to='packages.UserPackage'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user_auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='user_auth.UserAuthModel'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user_event',
            field=models.ForeignKey(help_text='event of this plan', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='event.UserEvent'),
        ),
    ]
