output:
	./manage.py loaddata ./core/apps/evaluation/session_evaluation/fixtures/session_score_categories_truth_table_20200319.json
	./manage.py loaddata ./core/apps/training_zone/fixtures/training_zone_truth_table_20200318.json
	./manage.py loaddata ./core/apps/event/fixtures/event_demands_20200408.json
	./manage.py loaddata ./core/apps/event/fixtures/event_details_20200315.json
	./manage.py loaddata ./core/apps/event/fixtures/event_type_20200317.json
	./manage.py loaddata ./core/apps/event/fixtures/named_event_20200326.json
	./manage.py loaddata ./core/apps/session/fixtures/session_rules_truth_table_20200404.json
	./manage.py loaddata ./core/apps/session/fixtures/session_type_truth_table_20200402.json
	./manage.py loaddata ./core/apps/session/fixtures/session_truth_table_20200402.json
	./manage.py loaddata ./core/apps/session/fixtures/session_interval_truth_table_20200403.json
	./manage.py loaddata ./core/apps/session/fixtures/session_feedback_option_table_20210527.json
	./manage.py loaddata ./core/apps/week/fixtures/week_rules_truth_table_20200404.json
	./manage.py loaddata ./core/apps/user_profile/fixtures/user_activity_code_2020_06_27.json
	./manage.py loaddata ./core/apps/user_profile/fixtures/timezone_2020_07_10.json
	./manage.py loaddata ./core/apps/notification/fixtures/notification_type_2020_09_26.json
	./manage.py loaddata ./core/apps/achievements/fixtures/record_types_2021_02_03.json
	./manage.py loaddata ./core/apps/achievements/fixtures/record_levels_2021_02_03.json
	./manage.py loaddata ./core/apps/settings/fixtures/third_party_settings_2021_02_08.json
	./manage.py loaddata ./core/apps/packages/fixtures/package_20210630.json
	./manage.py loaddata ./core/apps/packages/fixtures/sub_package_20210630.json
	./manage.py loaddata ./core/apps/packages/fixtures/knowledge_hub_20211020.json
