# Generated by Django 3.0 on 2021-03-08 17:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0021_auto_20201019_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('title', models.CharField(help_text='Title of the Challenge e.g. March Distance Challenge', max_length=255)),
                ('challenge_type', models.IntegerField(help_text='Indicates type of a particular challenge')),
                ('start_date', models.DateField(help_text='Start date of the challenge')),
                ('end_date', models.DateField(help_text='End date of the challenge')),
                ('unit', models.CharField(help_text='Unit of the required value of a challenge e.g. km for distance challenge', max_length=30, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the challenge', null=True)),
                ('image_url', models.TextField(blank=True, help_text='Challenge background image url', null=True)),
                ('badge_url', models.TextField(blank=True, help_text='Challenge badge url', null=True)),
                ('share_link', models.TextField(blank=True, help_text='Challenge share url', null=True)),
            ],
            options={
                'verbose_name': 'Challenge',
                'db_table': 'challenge',
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_completed', models.BooleanField(default=False, help_text='Indicates if the challenge is completed or not')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='The date when the user signed up for the challenge')),
                ('completion_date', models.DateField(help_text='The date when the user completed the challenge', null=True)),
                ('achieved_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Value achieved for this challenge up until now', max_digits=20)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenge', to='challenges.Challenge')),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenge', to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'User Challenge',
                'db_table': 'user_challenge',
            },
        ),
    ]
