# Generated by Django 3.0 on 2021-03-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='target_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Target value for this challenge up until now', max_digits=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(help_text='Indicates type of a particular challenge', max_length=55),
        ),
    ]
