# Generated by Django 3.0 on 2021-03-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20210311_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary of the challenge', null=True),
        ),
    ]
