# Generated by Django 3.0 on 2021-03-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary target of the challenge, which will be shown in the take challenge tile under the challenge title', null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='target_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Target value for completing this challenge', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='achieved_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Value achieved for this challenge up until now', max_digits=20, null=True),
        ),
    ]
