# Generated by Django 3.0 on 2021-03-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20210313_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='completion_message_shown',
            field=models.BooleanField(default=False, help_text='Indicates if the challenge completionmessage is already shown or not'),
        ),
    ]
