# Generated by Django 3.0 on 2021-06-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_userchallenge_completion_message_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
    ]
