# Generated by Django 3.0 on 2020-02-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
        ('block', '0001_initial'),
        ('training_zone', '0001_initial'),
        ('week', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=255)),
                ('training_zone', models.CharField(max_length=10)),
                ('structured', models.BooleanField()),
                ('goal_hours', models.IntegerField()),
                ('session_date_time', models.DateTimeField()),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Plan')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='week.Week')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_zone.TrainingZone')),
            ],
            options={
                'verbose_name': 'Session Table',
                'db_table': 'session',
            },
        ),
    ]
