# Generated by Django 3.0 on 2020-02-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='training_zone',
        ),
    ]
