# Generated by Django 3.0 on 2020-02-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_session_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='goal_hours',
            field=models.FloatField(null=True),
        ),
    ]
