# Generated by Django 3.0 on 2020-03-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20200214_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Intervals'), (2, 'Easy'), (3, 'Long'), (4, 'High Intensity Maintenence'), (5, 'Event'), (6, 'Recovery Day'), (7, 'Commute')], null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='structured',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
