# Generated by Django 3.0 on 2020-03-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('training_zone', '0002_auto_20200205_1705'),
        ('session', '0007_auto_20200307_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='actual_ctl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='actual_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='actual_pss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='duration_in_Z0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='duration_in_Z1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='duration_in_Z2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='duration_in_Z3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='duration_in_Z4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='duration_in_Z5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='duration_in_Z6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='duration_in_Z7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='physiological_goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='planned_ctl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='planned_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='planned_pss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='training_goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.UserAuthModel'),
        ),
        migrations.AddField(
            model_name='session',
            name='zone_focus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training_zone.TrainingZone'),
        ),
        migrations.CreateModel(
            name='SessionInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_name', models.CharField(default='N', max_length=10)),
                ('time_in_minutes', models.IntegerField(blank=True, null=True)),
                ('time_in_seconds', models.IntegerField(blank=True, null=True)),
                ('percentage_ftp_lower', models.IntegerField(blank=True, null=True)),
                ('percentage_ftp_upper', models.IntegerField(blank=True, null=True)),
                ('percentage_fthr_lower', models.IntegerField(blank=True, null=True)),
                ('percentage_fthr_upper', models.IntegerField(blank=True, null=True)),
                ('rpe_lower', models.IntegerField(blank=True, null=True)),
                ('rpe_upper', models.IntegerField(blank=True, null=True)),
                ('cadence_lower', models.IntegerField(blank=True, null=True)),
                ('cadence_upper', models.IntegerField(blank=True, null=True)),
                ('pss', models.IntegerField(blank=True, null=True)),
                ('zone_focus', models.IntegerField(blank=True, null=True)),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.Session')),
            ],
        ),
    ]
