# Generated by Django 3.0 on 2020-03-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_auto_20200328_1542'),
        ('session', '0009_auto_20200326_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='plan',
        ),
        migrations.AddField(
            model_name='session',
            name='day',
            field=models.ForeignKey(default=1, help_text='day of this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='daily.Daily'),
            preserve_default=False,
        ),
    ]
