# Generated by Django 3.0 on 2020-03-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0010_auto_20200328_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='block',
        ),
        migrations.RemoveField(
            model_name='session',
            name='week',
        ),
    ]
