# Generated by Django 3.0 on 2020-03-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0010_auto_20200331_1847'),
        ('user_auth', '0001_initial'),
        ('session', '0011_auto_20200328_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='UserSession',
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name': 'User Session Table'},
        ),
        migrations.AlterModelTable(
            name='usersession',
            table='user_session',
        ),
    ]
