# Generated by Django 3.0 on 2020-04-02 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0012_auto_20200402_1840'),
        ('user_auth', '0002_auto_20200330_0016'),
        ('session', '0012_auto_20200331_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
                ('target_zone', models.IntegerField(null=True)),
                ('number_of_sessions', models.IntegerField(null=True)),
                ('average_intensity', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Session Type TT',
                'db_table': 'session_type',
            },
        ),
        migrations.AlterModelOptions(
            name='sessioninterval',
            options={'verbose_name': 'Session Interval TT'},
        ),
        migrations.RenameField(
            model_name='usersession',
            old_name='session_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='sessioninterval',
            name='percentage_fthr_lower',
        ),
        migrations.RemoveField(
            model_name='sessioninterval',
            name='percentage_fthr_upper',
        ),
        migrations.RemoveField(
            model_name='sessioninterval',
            name='percentage_ftp_lower',
        ),
        migrations.RemoveField(
            model_name='sessioninterval',
            name='percentage_ftp_upper',
        ),
        migrations.RemoveField(
            model_name='sessioninterval',
            name='time_in_seconds',
        ),
        migrations.RemoveField(
            model_name='sessioninterval',
            name='zone_focus',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.AddField(
            model_name='sessioninterval',
            name='fthr_percentage_lower',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessioninterval',
            name='fthr_percentage_upper',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessioninterval',
            name='ftp_percentage_lower',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessioninterval',
            name='ftp_percentage_upper',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessioninterval',
            name='key_interval_tag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sessioninterval',
            name='padding_interval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user_auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='user_auth.UserAuthModel'),
        ),
        migrations.AlterField(
            model_name='sessioninterval',
            name='cadence_lower',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessioninterval',
            name='cadence_upper',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessioninterval',
            name='pss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessioninterval',
            name='rpe_lower',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessioninterval',
            name='rpe_upper',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessioninterval',
            name='time_in_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='day',
            field=models.ForeignKey(help_text='day of this session', on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='daily.UserDay'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserSessionInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padding_interval', models.BooleanField(default=False)),
                ('interval_name', models.CharField(default='N', max_length=10)),
                ('time_in_minutes', models.FloatField(blank=True, null=True)),
                ('ftp_percentage_lower', models.FloatField(blank=True, null=True)),
                ('ftp_percentage_upper', models.FloatField(blank=True, null=True)),
                ('fthr_percentage_lower', models.FloatField(blank=True, null=True)),
                ('fthr_percentage_upper', models.FloatField(blank=True, null=True)),
                ('rpe_lower', models.FloatField(blank=True, null=True)),
                ('rpe_upper', models.FloatField(blank=True, null=True)),
                ('cadence_lower', models.FloatField(blank=True, null=True)),
                ('cadence_upper', models.FloatField(blank=True, null=True)),
                ('pss', models.FloatField(blank=True, null=True)),
                ('key_interval_tag', models.BooleanField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_completed', models.BooleanField(blank=True, null=True)),
                ('user_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_session_intervals', to='session.UserSession')),
            ],
            options={
                'verbose_name': 'User Session Interval',
                'db_table': 'user_session_interval',
            },
        ),
        migrations.CreateModel(
            name='SessionRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_focus', models.IntegerField(null=True)),
                ('typical_intensity', models.FloatField(null=True)),
                ('minimum_pss', models.FloatField(null=True)),
                ('max_num_of_selected_session_type_per_week', models.IntegerField(null=True)),
                ('session_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.SessionType')),
            ],
            options={
                'verbose_name': 'Session Rules',
                'db_table': 'session_rules',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=255)),
                ('duration_in_minutes', models.FloatField(null=True)),
                ('intensity', models.FloatField(null=True)),
                ('pss', models.FloatField(null=True)),
                ('session_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.SessionType')),
            ],
            options={
                'verbose_name': 'Session TT',
                'db_table': 'session',
            },
        ),
        migrations.AlterField(
            model_name='sessioninterval',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.Session'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='session.SessionType'),
            preserve_default=False,
        ),
    ]
