# Generated by Django 3.0 on 2020-04-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0013_auto_20200402_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_type_id',
            new_name='session_type',
        ),
    ]
