# Generated by Django 3.0 on 2020-04-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0016_auto_20200402_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessioninterval',
            old_name='padding_interval',
            new_name='is_padding_interval',
        ),
        migrations.RenameField(
            model_name='sessioninterval',
            old_name='interval_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_typey',
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='session.SessionType'),
        ),
        migrations.AlterField(
            model_name='sessioninterval',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_intervals', to='session.Session'),
        ),
    ]
