# Generated by Django 3.0 on 2020-04-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0017_auto_20200402_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.CharField(max_length=1023),
        ),
    ]
