# Generated by Django 3.0 on 2020-04-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0018_auto_20200402_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessioninterval',
            old_name='session_id',
            new_name='session',
        ),
    ]
