# Generated by Django 3.0 on 2020-04-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0020_auto_20200404_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionrules',
            old_name='session_type_id',
            new_name='session_type',
        ),
    ]
