# Generated by Django 3.0 on 2020-04-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0021_auto_20200404_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioninterval',
            name='time_in_minutes',
        ),
        migrations.AddField(
            model_name='sessioninterval',
            name='time_in_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
