# Generated by Django 3.0 on 2020-04-08 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0027_remove_sessionrules_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_types', to='session.SessionRules'),
        ),
    ]
