# Generated by Django 3.0 on 2020-04-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0029_auto_20200409_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_interval',
            new_name='interval',
        ),
    ]
