# Generated by Django 3.0 on 2020-04-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0030_auto_20200409_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='interval',
        ),
        migrations.AddField(
            model_name='sessioninterval',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_intervals', to='session.Session'),
        ),
    ]
