# Generated by Django 3.0 on 2020-04-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0031_auto_20200409_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='ride_summary',
            field=models.TextField(blank=True, help_text='User ride Summary', null=True),
        ),
    ]
