# Generated by Django 3.0 on 2020-04-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0033_auto_20200410_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontype',
            name='name',
            field=models.CharField(default='REST', max_length=55),
            preserve_default=False,
        ),
    ]
