# Generated by Django 3.0 on 2020-04-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0034_auto_20200410_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='description',
            field=models.CharField(default=1, help_text='User Session description', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersession',
            name='planned_intensity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersession',
            name='planned_load',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='cadence_lower',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='cadence_upper',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='fthr_percentage_lower',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='fthr_percentage_upper',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='ftp_percentage_lower',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='ftp_percentage_upper',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='interval_name',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='key_interval_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='pss',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='rpe_lower',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='rpe_upper',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='time_in_minutes',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
