# Generated by Django 3.0 on 2020-04-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0035_auto_20200410_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='sessioninterval',
            name='name',
            field=models.CharField(default='N', max_length=550),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='name',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='description',
            field=models.TextField(help_text='User Session description'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='fitfile_name',
            field=models.CharField(max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='name',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='usersessioninterval',
            name='interval_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
