# Generated by Django 3.0 on 2020-04-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0036_auto_20200411_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='planned_load',
            field=models.FloatField(default=0.0),
        ),
    ]
