# Generated by Django 3.0 on 2020-04-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0038_auto_20200411_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='fitfile_name',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
