# Generated by Django 3.0 on 2020-04-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0039_auto_20200411_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersessioninterval',
            old_name='time_in_minutes',
            new_name='time_in_seconds',
        ),
    ]
