# Generated by Django 3.0 on 2020-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0040_auto_20200412_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='actual_pss',
            field=models.FloatField(default=0.0),
        ),
    ]
