# Generated by Django 3.0 on 2020-04-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0041_auto_20200413_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='actual_duration_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='actual_pss_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='actual_sqs_session_score',
            field=models.FloatField(default=0.0),
        ),
    ]
