# Generated by Django 3.0 on 2020-04-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0042_auto_20200413_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='actual_duration_score',
            new_name='duration_score',
        ),
        migrations.RenameField(
            model_name='usersession',
            old_name='actual_pss_score',
            new_name='pss_score',
        ),
        migrations.RenameField(
            model_name='usersession',
            old_name='actual_sqs_session_score',
            new_name='sqs_session_score',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='planned_duration_score',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='planned_pss_score',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='planned_sqs_session_score',
        ),
    ]
