# Generated by Django 3.0 on 2020-04-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0044_auto_20200413_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='zone_focus',
            field=models.IntegerField(),
        ),
    ]
