# Generated by Django 3.0 on 2020-05-09 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0002_auto_20200509_1316'),
        ('session', '0047_usersession_actual_distance_in_meters'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='garmin_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_session', to='garmin.GarminData'),
        ),
    ]
