# Generated by Django 3.0 on 2020-05-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0048_usersession_garmin_data'),
    ]

    operations = [
        migrations.RunSQL(
            "update user_session_interval "
            "set fthr_percentage_upper = 999, fthr_percentage_lower = 106.01 "
            "where fthr_percentage_upper = 0.00 and fthr_percentage_lower = 0.00"
        ),
        migrations.RunSQL(
            "update user_session_interval "
            "set fthr_percentage_upper = 106.00 "
            "where fthr_percentage_upper = 0.00"
        )
    ]
