# Generated by Django 3.0 on 2020-05-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0050_fix_recovery_interval_fthr'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='planned_time_in_hr_zone',
            field=models.TextField(blank=True, help_text='Actual Time in zones in heart rate data', null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='planned_time_in_power_zone',
            field=models.TextField(blank=True, help_text='Actual Time in zones in power data', null=True),
        ),
    ]
