# Generated by Django 3.0 on 2020-05-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0051_auto_20200527_1209'),
    ]

    operations = [
        migrations.RunSQL(
            "update user_session "
            "set planned_time_in_power_zone = planned_time_in_zones"
        )
    ]
