# Generated by Django 3.0 on 2020-05-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0052_time_in_zone_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='actual_time_in_zones',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='planned_time_in_zones',
        ),
    ]
