# Generated by Django 3.0 on 2020-07-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0053_auto_20200527_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='goal_hours',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='physiological_goal',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='structured',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='training_goal',
        ),
    ]
