# Generated by Django 3.0 on 2020-07-07 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0005_auto_20200628_0008'),
        ('session', '0054_auto_20200708_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='garmin_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_session', to='garmin.GarminData'),
        ),
    ]
