# Generated by Django 3.0 on 2020-07-13 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0055_auto_20200708_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='is_pad_applicable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='pad_pss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='pad_time_in_seconds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='session',
            field=models.ForeignKey(blank=True, help_text='session from truth table', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='session.Session'),
        ),
    ]
