# Generated by Django 3.0 on 2020-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0056_auto_20200713_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
