# Generated by Django 3.0 on 2020-08-19 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
        ('session', '0058_auto_20200811_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualsession',
            name='strava_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_session', to='strava.StravaData'),
        ),
    ]
