# Generated by Django 3.0 on 2020-08-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_thirdpartysettings'),
        ('session', '0059_actualsession_strava_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualsession',
            name='third_party_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_sessions', to='settings.ThirdPartySettings'),
        ),
    ]
