# Generated by Django 3.0 on 2020-08-26 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_thirdpartysettings_code'),
        ('session', '0060_actualsession_third_party_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualsession',
            name='third_party_settings',
        ),
        migrations.AddField(
            model_name='actualsession',
            name='third_party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_sessions', to='settings.ThirdPartySettings'),
        ),
    ]
