# Generated by Django 3.0 on 2020-12-05 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillar', '0002_auto_20201204_1942'),
        ('session', '0061_auto_20200827_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualsession',
            name='pillar_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_session', to='pillar.Activity'),
        ),
    ]
