# Generated by Django 3.0 on 2020-12-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0062_useraway'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraway',
            name='away_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraway',
            name='away_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
