# Generated by Django 3.0 on 2020-12-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0063_auto_20201204_1712'),
        ('session', '0062_actualsession_pillar_data'),
    ]

    operations = [
    ]
