# Generated by Django 3.0 on 2020-12-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0064_merge_20201205_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAwayInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_start_date', models.DateField(blank=True, null=True)),
                ('away_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Away Intervals',
                'db_table': 'user_away_interval',
            },
        ),
        migrations.RemoveField(
            model_name='useraway',
            name='away_end_date',
        ),
        migrations.RemoveField(
            model_name='useraway',
            name='away_start_date',
        ),
        migrations.AddField(
            model_name='useraway',
            name='away_interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_away_intervals', to='session.UserAwayInterval'),
        ),
    ]
