# Generated by Django 3.0 on 2020-12-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0065_auto_20201215_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraway',
            name='reason',
        ),
        migrations.AddField(
            model_name='userawayinterval',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
