# Generated by Django 3.0 on 2020-12-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0066_auto_20201215_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userawayinterval',
            name='away_end_date',
        ),
        migrations.RemoveField(
            model_name='userawayinterval',
            name='away_start_date',
        ),
        migrations.AddField(
            model_name='userawayinterval',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userawayinterval',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
