# Generated by Django 3.0 on 2020-12-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0067_auto_20201215_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraway',
            name='away_interval',
        ),
    ]
