# Generated by Django 3.0 on 2020-12-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0069_useraway_interval_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userawayinterval',
            name='interval_code',
            field=models.UUIDField(blank=True, editable=False, help_text='away interval code', null=True),
        ),
    ]
