# Generated by Django 3.0 on 2020-12-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0070_userawayinterval_interval_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualsession',
            name='show_pairing_message',
            field=models.BooleanField(default=True),
        ),
    ]
