# Generated by Django 3.0 on 2020-12-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0071_actualsession_show_pairing_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualsession',
            name='session_label',
            field=models.CharField(blank=True, default='TRAINING_SESSION', help_text='Type of the Activity',
                                   max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='activity_name',
            field=models.CharField(blank=True, help_text='User given name of the activity', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='description',
            field=models.TextField(blank=True, help_text="User's description of the activity", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='effort_level',
            field=models.IntegerField(blank=True, help_text='How hard or stressful the activity was for the athlete', null=True),
        ),
    ]
