# Generated by Django 3.0 on 2021-01-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0073_auto_20210108_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionscore',
            name='key_zone_performance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
