# Generated by Django 3.0 on 2021-02-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0074_sessionscore_key_zone_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualsession',
            name='code',
            field=models.UUIDField(editable=False, help_text='Unique code for each actual session', null=True),
        ),
    ]
