# Generated by Django 3.0 on 2021-03-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0076_actualsession_local_session_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualsession',
            name='athlete_activity_code',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
