# Generated by Django 3.0 on 2021-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0078_actualsession_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualsession',
            name='elevation_gain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
