# Generated by Django 3.0 on 2021-05-04 05:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0079_actualsession_elevation_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualsession',
            name='actual_intervals',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
