# Generated by Django 3.0 on 2021-03-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0079_actualsession_elevation_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
