# Generated by Django 3.0 on 2021-04-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0081_session_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualsession',
            name='athlete_activity_code',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
