# Generated by Django 3.0 on 2021-05-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0080_actualsession_actual_intervals'),
        ('session', '0082_auto_20210416_0614'),
    ]

    operations = [
    ]
