# Generated by Django 3.0 on 2021-05-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0081_auto_20210518_0648'),
        ('session', '0083_merge_20210510_1013'),
    ]

    operations = [
    ]
