# Generated by Django 3.0 on 2021-05-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0083_merge_20210510_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFeedbackOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_code', models.IntegerField(help_text='Unique integer code for the available feedback options')),
                ('option_text', models.CharField(help_text='Feedback option description', max_length=255)),
            ],
            options={
                'verbose_name': 'Session Feedback Options',
                'db_table': 'session_feedback_option',
            },
        ),
        migrations.AddField(
            model_name='actualsession',
            name='feedback_explanation',
            field=models.TextField(help_text="User's explanation about the session", null=True),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='feedback_option_code',
            field=models.IntegerField(help_text='Option code for the predefined feedback options', null=True),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='session_followed_as_planned',
            field=models.BooleanField(help_text='User input, if the user was able to follow the session according to the plan or not', null=True),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='show_feedback_popup',
            field=models.BooleanField(default=True, help_text='If session feedback popup needs to be shown or not'),
        ),
    ]
