# Generated by Django 3.0 on 2021-06-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0084_auto_20210527_1536'),
        ('session', '0084_merge_20210519_0720'),
    ]

    operations = [
    ]
