# Generated by Django 3.0 on 2021-06-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0085_merge_20210601_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualsession',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='useraway',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
    ]
