# Generated by Django 3.2.5 on 2021-08-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0086_auto_20210628_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninterval',
            name='mhr_percentage_lower',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='sessioninterval',
            name='mhr_percentage_upper',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
