# Generated by Django 3.2.5 on 2021-08-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0086_auto_20210628_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualsession',
            name='actual_intervals',
            field=models.JSONField(null=True),
        ),
    ]
