# Generated by Django 3.2.5 on 2021-08-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0087_alter_actualsession_actual_intervals'),
        ('session', '0087_auto_20210812_1958'),
    ]

    operations = [
    ]
