# Generated by Django 3.2.5 on 2021-10-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0088_merge_20210824_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualsession',
            old_name='local_session_date_time',
            new_name='utc_session_date_time',
        ),
    ]
