# Generated by Django 3.2.5 on 2021-12-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0089_rename_local_session_date_time_actualsession_utc_session_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersessioninterval',
            name='user_session',
        ),
        migrations.RemoveField(
            model_name='actualsession',
            name='garmin_data',
        ),
        migrations.RemoveField(
            model_name='actualsession',
            name='strava_data',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
        migrations.DeleteModel(
            name='UserSessionInterval',
        ),
    ]
