# Generated by Django 3.0 on 2020-11-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationdetail',
            options={'ordering': ['sequence'], 'verbose_name': 'Information Detail'},
        ),
        migrations.AlterModelOptions(
            name='informationsection',
            options={'ordering': ['sequence'], 'verbose_name': 'Information Section'},
        ),
        migrations.AddField(
            model_name='informationdetail',
            name='sequence',
            field=models.IntegerField(default=1, verbose_name='Sequence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informationsection',
            name='sequence',
            field=models.IntegerField(default=1, verbose_name='Sequence'),
            preserve_default=False,
        ),
    ]
