# Generated by Django 3.0 on 2020-02-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block')),
            ],
            options={
                'verbose_name': 'Week Table',
                'db_table': 'week',
            },
        ),
    ]
