# Generated by Django 3.0 on 2020-03-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_auto_20200310_1803'),
        ('week', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='actual_atl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='actual_ctl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='actual_pss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='actual_tsb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='target_atl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='target_ctl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='target_pss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='target_tsb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='block.Block'),
        ),
    ]
