# Generated by Django 3.0 on 2020-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0002_auto_20200310_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='time_in_Z0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='time_in_Z1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='time_in_Z2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='time_in_Z3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='time_in_Z4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='time_in_Z5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='time_in_Z6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='time_in_Z7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='week',
            table='user_week_plan',
        ),
    ]
