# Generated by Django 3.0 on 2020-03-27 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_auto_20200327_1318'),
        ('week', '0003_auto_20200326_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={},
        ),
        migrations.RemoveField(
            model_name='week',
            name='actual_atl',
        ),
        migrations.RemoveField(
            model_name='week',
            name='actual_ctl',
        ),
        migrations.RemoveField(
            model_name='week',
            name='actual_pss',
        ),
        migrations.RemoveField(
            model_name='week',
            name='actual_tsb',
        ),
        migrations.RemoveField(
            model_name='week',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='week',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='week',
            name='target_atl',
        ),
        migrations.RemoveField(
            model_name='week',
            name='target_ctl',
        ),
        migrations.RemoveField(
            model_name='week',
            name='target_pss',
        ),
        migrations.RemoveField(
            model_name='week',
            name='target_tsb',
        ),
        migrations.RemoveField(
            model_name='week',
            name='time_in_Z0',
        ),
        migrations.RemoveField(
            model_name='week',
            name='time_in_Z1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='time_in_Z2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='time_in_Z3',
        ),
        migrations.RemoveField(
            model_name='week',
            name='time_in_Z4',
        ),
        migrations.RemoveField(
            model_name='week',
            name='time_in_Z5',
        ),
        migrations.RemoveField(
            model_name='week',
            name='time_in_Z6',
        ),
        migrations.RemoveField(
            model_name='week',
            name='time_in_Z7',
        ),
        migrations.RemoveField(
            model_name='week',
            name='type',
        ),
        migrations.RemoveField(
            model_name='week',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='week',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='week',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='end date of the week'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='start date of the week'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='week_type',
            field=models.CharField(choices=[('BUILD', 'Build week'), ('RECOVERY', 'Recovery week')], default='BUILD', help_text='type of week', max_length=20),
        ),
        migrations.AddField(
            model_name='week',
            name='zone_focus',
            field=models.FloatField(blank=True, default=0.0, help_text='zone focus value for this block', null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='block',
            field=models.ForeignKey(default=1, help_text='block of this week', on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='block.Block'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='week',
            table=None,
        ),
    ]
