# Generated by Django 3.0 on 2020-03-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0004_auto_20200327_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='end_date',
            field=models.DateField(blank=True, help_text='end date of the week'),
        ),
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(blank=True, help_text='start date of the week'),
        ),
    ]
