# Generated by Django 3.0 on 2020-03-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0005_auto_20200327_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='zone_focus',
            field=models.IntegerField(blank=True, default=0.0, help_text='zone focus value for this block', null=True),
        ),
    ]
