# Generated by Django 3.0 on 2020-03-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0006_auto_20200327_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='ramp_rate',
            field=models.FloatField(blank=True, help_text='calculated ramp rate for this week', null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='zone_focus',
            field=models.IntegerField(blank=True, default=0, help_text='zone focus value for this week', null=True),
        ),
    ]
