# Generated by Django 3.0 on 2020-03-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0007_auto_20200328_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='ramp_rate',
            new_name='target_ramp_rate',
        ),
    ]
