# Generated by Django 3.0 on 2020-03-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0008_auto_20200328_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='sunday_ramp_rate',
            field=models.FloatField(blank=True, help_text='calculated ramp rate for last sunday of this week', null=True),
        ),
    ]
