# Generated by Django 3.0 on 2020-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0009_week_sunday_ramp_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='sunday_ramp_rate',
        ),
        migrations.AddField(
            model_name='week',
            name='sunday_max_load',
            field=models.FloatField(blank=True, help_text='calculated max load for last sunday of this week', null=True),
        ),
    ]
