# Generated by Django 3.0 on 2020-03-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0010_auto_20200328_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='end_date',
            field=models.DateField(blank=True, help_text='end date of the week', null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(blank=True, help_text='start date of the week', null=True),
        ),
    ]
