# Generated by Django 3.0 on 2020-03-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0010_auto_20200331_1847'),
        ('block', '0017_auto_20200331_1849'),
        ('week', '0011_auto_20200328_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Week',
            new_name='UserWeek',
        ),
        migrations.AlterModelOptions(
            name='userweek',
            options={'verbose_name': 'User Week Table'},
        ),
        migrations.AlterModelTable(
            name='userweek',
            table='user_week',
        ),
    ]
