# Generated by Django 3.0 on 2020-04-02 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0013_auto_20200402_1840'),
        ('block', '0018_auto_20200402_1840'),
        ('week', '0012_auto_20200331_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userweek',
            name='block',
        ),
        migrations.RemoveField(
            model_name='userweek',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='userweek',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='userweek',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userweek',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userweek',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userweek',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userweek',
            name='user_block',
            field=models.ForeignKey(default=1, help_text='block of this week', on_delete=django.db.models.deletion.CASCADE, related_name='user_weeks', to='block.UserBlock'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WeekRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_number', models.IntegerField(null=True)),
                ('zone_focus', models.IntegerField(null=True)),
                ('session_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.SessionType')),
            ],
        ),
    ]
