# Generated by Django 3.0 on 2020-04-03 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0019_auto_20200402_2154'),
        ('week', '0013_auto_20200402_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweek',
            name='session_type',
            field=models.ForeignKey(default=1, help_text='session type of the week', on_delete=django.db.models.deletion.CASCADE, related_name='user_weeks', to='session.SessionType'),
            preserve_default=False,
        ),
    ]
