# Generated by Django 3.0 on 2020-04-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0014_userweek_session_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekrules',
            options={'verbose_name': 'Week Rules'},
        ),
        migrations.AlterModelTable(
            name='weekrules',
            table='week_rules',
        ),
    ]
