# Generated by Django 3.0 on 2020-04-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0015_auto_20200403_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweek',
            name='actual_acute_load',
            field=models.FloatField(blank=True, default=0.0, help_text='actual acute load of a user in week', null=True),
        ),
        migrations.AddField(
            model_name='userweek',
            name='actual_freshness',
            field=models.FloatField(blank=True, default=0.0, help_text='actual freshness of a user in a week', null=True),
        ),
        migrations.AddField(
            model_name='userweek',
            name='actual_load',
            field=models.FloatField(blank=True, default=0.0, help_text='actual load of a user in week', null=True),
        ),
        migrations.AddField(
            model_name='userweek',
            name='actual_pss',
            field=models.FloatField(blank=True, default=0.0, help_text='actual pss of a user in week', null=True),
        ),
    ]
