# Generated by Django 3.0 on 2020-04-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0016_auto_20200405_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweek',
            name='commute_pss_week',
            field=models.FloatField(blank=True, default=0.0, help_text='commute pss of a user in week', null=True),
        ),
    ]
