# Generated by Django 3.0 on 2020-04-08 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0026_usersession_description'),
        ('week', '0017_userweek_commute_pss_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweek',
            name='session_type',
            field=models.ForeignKey(blank=True, help_text='session type of the week', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_weeks', to='session.SessionType'),
        ),
    ]
