# Generated by Django 3.0 on 2020-04-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0018_auto_20200408_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweek',
            name='zone_focus',
            field=models.IntegerField(default=0, help_text='zone focus value for this week'),
        ),
    ]
