# Generated by Django 3.0 on 2020-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0020_userweek_planned_pss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweek',
            name='actual_acute_load',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='actual acute load of a user in week', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userweek',
            name='actual_freshness',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='actual freshness of a user in a week', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userweek',
            name='actual_load',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='actual load of a user in week', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userweek',
            name='actual_pss',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='actual pss of a user in week', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userweek',
            name='commute_pss_week',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='commute pss of a user in week', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userweek',
            name='planned_pss',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='actual load of a user in week', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userweek',
            name='sunday_max_load',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='calculated max load for last sunday of this week', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userweek',
            name='target_ramp_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='calculated ramp rate for this week', max_digits=20),
        ),
    ]
