# Generated by Django 3.0 on 2020-04-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0021_auto_20200419_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userweek',
            name='target_ramp_rate',
        ),
    ]
