# Generated by Django 3.0 on 2020-08-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0022_remove_userweek_target_ramp_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweek',
            name='week_code',
            field=models.UUIDField(editable=False, help_text='Unique week code for each week', null=True),
        ),
    ]
