# Generated by Django 3.0 on 2020-08-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0024_auto_20200812_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweek',
            name='week_code',
            field=models.UUIDField(editable=False, help_text='Unique week code for each week', null=True),
        ),
    ]
