# Generated by Django 3.0 on 2020-11-26 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0021_auto_20201019_1708'),
        ('week', '0026_userweek_block_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweek',
            name='user_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_weeks', to='user_auth.UserAuthModel'),
        ),
    ]
