# Generated by Django 3.0 on 2021-06-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0027_userweek_user_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweek',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
    ]
