# Generated by Django 3.2.5 on 2021-07-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0028_userweek_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user_id', models.UUIDField()),
                ('code', models.UUIDField(help_text='Unique code for each week analysis')),
                ('week_no', models.IntegerField()),
                ('total_weeks_in_block', models.IntegerField()),
                ('week_title', models.CharField(max_length=255)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('current_week_remarks', models.JSONField()),
                ('last_week_comparison_remarks', models.TextField()),
                ('tips_for_next_week', models.TextField()),
                ('actual_time_in_power_zones', models.JSONField()),
                ('planned_time_in_power_zones', models.JSONField()),
                ('actual_time_in_hr_zones', models.JSONField()),
                ('planned_time_in_hr_zones', models.JSONField()),
                ('feel_feedback', models.CharField(choices=[('GREAT', 'Great'), ('OK', 'Ok'), ('HARD', 'Hard')], max_length=10, null=True)),
                ('week_feedback', models.CharField(max_length=255, null=True)),
                ('suggestion_feedback', models.CharField(max_length=255, null=True)),
                ('utp_summary', models.TextField()),
                ('utp_reason', models.TextField()),
            ],
            options={
                'verbose_name': 'Week Analysis',
                'db_table': 'week_analysis',
            },
        ),
    ]
