# Generated by Django 3.2.5 on 2021-08-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0029_weekanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekanalysis',
            name='total_weeks_in_block',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weekanalysis',
            name='week_no',
            field=models.IntegerField(null=True),
        ),
    ]
