# Generated by Django 3.2.5 on 2021-08-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0030_auto_20210803_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekanalysis',
            name='is_fthr_available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekanalysis',
            name='is_ftp_available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
