# Generated by Django 3.2.5 on 2021-08-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0031_auto_20210804_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekanalysis',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Distance in meters', max_digits=20),
        ),
        migrations.AddField(
            model_name='weekanalysis',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='weekanalysis',
            name='elevation',
            field=models.IntegerField(default=0, help_text='Elevation in meters'),
        ),
        migrations.AddField(
            model_name='weekanalysis',
            name='pss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weekanalysis',
            name='total_rides',
            field=models.IntegerField(default=0),
        ),
    ]
