# Generated by Django 3.2.5 on 2021-08-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0032_auto_20210805_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekanalysis',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Duration in minutes', max_digits=20),
        ),
    ]
