# Generated by Django 3.2.5 on 2021-08-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0033_alter_weekanalysis_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekanalysis',
            name='current_week_remarks',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='weekanalysis',
            name='last_week_comparison_remarks',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='weekanalysis',
            name='tips_for_next_week',
            field=models.JSONField(null=True),
        ),
    ]
