# Generated by Django 3.2.5 on 2021-09-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0034_auto_20210805_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekanalysis',
            name='actual_time_above_zone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weekanalysis',
            name='actual_time_in_zone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weekanalysis',
            name='average_sas',
            field=models.FloatField(default=0.0),
        ),
    ]
