# Generated by Django 3.2.5 on 2021-09-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0035_auto_20210923_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekanalysis',
            name='utp_reason',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='weekanalysis',
            name='utp_summary',
            field=models.JSONField(),
        ),
    ]
