# Generated by Django 3.2.5 on 2021-09-23 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0036_auto_20210923_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekanalysis',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
