# Generated by Django 3.0 on 2020-03-13 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('week', '0002_auto_20200310_1803'),
        ('block', '0003_auto_20200310_1803'),
        ('user_auth', '0001_initial'),
        ('plan', '0004_auto_20200310_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('max_ctl', models.FloatField(blank=True, null=True)),
                ('max_atl', models.FloatField(blank=True, null=True)),
                ('max_tsb', models.FloatField(blank=True, null=True)),
                ('max_pss', models.FloatField(blank=True, null=True)),
                ('target_ctl', models.FloatField(blank=True, null=True)),
                ('target_atl', models.FloatField(blank=True, null=True)),
                ('target_tsb', models.FloatField(blank=True, null=True)),
                ('target_pss', models.FloatField(blank=True, null=True)),
                ('planned_ctl', models.FloatField(blank=True, null=True)),
                ('planned_atl', models.FloatField(blank=True, null=True)),
                ('planned_tsb', models.FloatField(blank=True, null=True)),
                ('planned_pss', models.FloatField(blank=True, null=True)),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Plan')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.UserAuthModel')),
                ('week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='week.Week')),
            ],
        ),
    ]
