# Generated by Django 3.0 on 2020-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'verbose_name': 'User Daily Data Table'},
        ),
        migrations.AddField(
            model_name='daily',
            name='actual_atl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='actual_ctl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='actual_pss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='actual_tsb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='time_in_Z0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='time_in_Z1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='time_in_Z2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='time_in_Z3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='time_in_Z4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='time_in_Z5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='time_in_Z6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='time_in_Z7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='daily',
            table='user_daily_plan',
        ),
    ]
