# Generated by Django 3.0 on 2020-03-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0010_auto_20200328_1325'),
        ('daily', '0003_auto_20200326_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='plan_id',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='week_id',
        ),
        migrations.AddField(
            model_name='daily',
            name='week',
            field=models.ForeignKey(default=1, help_text='week of this day', on_delete=django.db.models.deletion.CASCADE, related_name='days', to='week.Week'),
            preserve_default=False,
        ),
    ]
