# Generated by Django 3.0 on 2020-03-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('week', '0011_auto_20200328_1622'),
        ('session', '0011_auto_20200328_1622'),
        ('daily', '0005_auto_20200328_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily',
            new_name='Day',
        ),
    ]
