# Generated by Django 3.0 on 2020-03-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0007_auto_20200328_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
