# Generated by Django 3.0 on 2020-03-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0008_auto_20200328_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='prs_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='recovery_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='actual_pss',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
