# Generated by Django 3.0 on 2020-03-31 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0011_auto_20200328_1622'),
        ('week', '0011_auto_20200328_1622'),
        ('user_auth', '0001_initial'),
        ('daily', '0009_auto_20200329_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day',
            new_name='UserDay',
        ),
        migrations.AlterModelOptions(
            name='userday',
            options={'verbose_name': 'User Daily Table'},
        ),
        migrations.AlterModelTable(
            name='userday',
            table='user_day',
        ),
    ]
