# Generated by Django 3.0 on 2020-04-02 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0012_auto_20200331_1902'),
        ('user_auth', '0002_auto_20200330_0016'),
        ('daily', '0011_auto_20200401_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userday',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userday',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userday',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userday',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userday',
            name='user_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_days', to='user_auth.UserAuthModel'),
        ),
        migrations.AlterField(
            model_name='userday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userday',
            name='week',
            field=models.ForeignKey(help_text='week of this day', on_delete=django.db.models.deletion.CASCADE, related_name='user_days', to='week.UserWeek'),
        ),
    ]
