# Generated by Django 3.0 on 2020-04-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0013_auto_20200402_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userday',
            options={'verbose_name': 'User Day Table'},
        ),
    ]
