# Generated by Django 3.0 on 2020-04-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0018_userday_zone_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userday',
            name='training_pss_by_freshness',
            field=models.FloatField(blank=True, help_text='Training PSS freshness approach', null=True),
        ),
        migrations.AddField(
            model_name='userday',
            name='training_pss_by_hours',
            field=models.FloatField(blank=True, help_text='Training PSS max hours approach', null=True),
        ),
        migrations.AddField(
            model_name='userday',
            name='training_pss_by_load',
            field=models.FloatField(blank=True, help_text='Training PSS load approach', null=True),
        ),
        migrations.AddField(
            model_name='userday',
            name='training_pss_by_max_ride',
            field=models.FloatField(blank=True, help_text='Training PSS max load approach', null=True),
        ),
    ]
