# Generated by Django 3.0 on 2020-04-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0019_auto_20200406_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userday',
            name='acute_load_post_commute',
            field=models.FloatField(blank=True, help_text='Acute Load post commute for day n', null=True),
        ),
        migrations.AddField(
            model_name='userday',
            name='load_post_commute',
            field=models.FloatField(blank=True, help_text='Load post commute for day n', null=True),
        ),
    ]
