# Generated by Django 3.0 on 2020-04-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0020_auto_20200406_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='userday',
            name='commute_pss_day',
            field=models.FloatField(blank=True, default=0.0, help_text='commute pss of a user in day', null=True),
        ),
    ]
