# Generated by Django 3.0 on 2020-04-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0022_userday_trainin_pss_final_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userday',
            name='prs_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userday',
            name='recovery_index',
            field=models.FloatField(default=0.0),
        ),
    ]
