# Generated by Django 3.0 on 2020-04-10 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0023_auto_20200410_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userday',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
