# Generated by Django 3.0 on 2020-04-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0024_auto_20200410_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userday',
            name='actual_pss',
            field=models.FloatField(default=0.0, help_text='actual pss of a user in day'),
        ),
        migrations.AlterField(
            model_name='userday',
            name='overall_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userday',
            name='sqs_today',
            field=models.FloatField(default=0.0),
        ),
    ]
