# Generated by Django 3.0 on 2020-04-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0025_auto_20200410_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userday',
            name='actual_acute_load',
            field=models.FloatField(default=0.0, help_text='actual acute load of a user in day'),
        ),
        migrations.AlterField(
            model_name='userday',
            name='actual_load',
            field=models.FloatField(default=0.0, help_text='actual load of a user in day'),
        ),
        migrations.AlterField(
            model_name='userday',
            name='planned_acute_load',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userday',
            name='planned_load',
            field=models.FloatField(default=0.0),
        ),
    ]
