# Generated by Django 3.0 on 2020-04-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0026_auto_20200410_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userday',
            name='planned_pss',
            field=models.FloatField(blank=True, default=0.0, help_text='actual load of a user in day', null=True),
        ),
    ]
