# Generated by Django 3.0 on 2020-04-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0027_auto_20200416_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userday',
            old_name='trainin_pss_final_value',
            new_name='training_pss_final_value',
        ),
    ]
