# Generated by Django 3.0 on 2020-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0029_auto_20200419_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userday',
            name='actual_acute_load',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='actual acute load of a user in day', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userday',
            name='actual_load',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='actual load of a user in day', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userday',
            name='actual_pss',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='actual pss of a user in day', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userday',
            name='overall_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userday',
            name='planned_acute_load',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userday',
            name='planned_load',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userday',
            name='prs_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userday',
            name='recovery_index',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userday',
            name='sqs_today',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
