# Generated by Django 3.0 on 2020-08-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0030_auto_20200419_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
