# Generated by Django 3.0 on 2020-08-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0032_auto_20200811_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='userday',
            name='week_code',
            field=models.UUIDField(editable=False, help_text='Unique week code for each week', null=True),
        ),
    ]
