# Generated by Django 3.0 on 2020-08-17 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0024_auto_20200812_2106'),
        ('daily', '0033_userday_week_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userday',
            name='day_code',
            field=models.UUIDField(editable=False, help_text='Unique day code for each day', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userday',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fit file upload'), (2, 'Morning calculation'), (3, 'Midnight calculation'), (4, 'Auto update training plan')], null=True),
        ),
        migrations.AlterField(
            model_name='userday',
            name='user_week',
            field=models.ForeignKey(blank=True, help_text='week of this day', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_days', to='week.UserWeek'),
        ),
    ]
