# Generated by Django 3.0 on 2020-08-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0034_auto_20200817_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userday',
            name='day_code',
            field=models.UUIDField(editable=False, help_text='Unique day code for each day', null=True),
        ),
    ]
