# Generated by Django 3.0 on 2020-11-18 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0021_auto_20201019_1708'),
        ('daily', '0035_auto_20200817_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('activity_date', models.DateField()),
                ('max_load', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('training_pss_by_load', models.DecimalField(decimal_places=2, default=0.0, help_text='Training PSS load approach', max_digits=20)),
                ('training_pss_by_freshness', models.DecimalField(decimal_places=2, default=0.0, help_text='Training PSS freshness approach', max_digits=20)),
                ('training_pss_by_max_ride', models.DecimalField(decimal_places=2, default=0.0, help_text='Training PSS max load approach', max_digits=20)),
                ('training_pss_by_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Training PSS max hours approach', max_digits=20)),
                ('training_pss_final_value', models.DecimalField(decimal_places=2, default=0.0, help_text='minimum of four different pss', max_digits=20)),
                ('planned_load', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('planned_acute_load', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('planned_pss', models.DecimalField(decimal_places=2, default=0.0, help_text='actual load of a user in day', max_digits=20)),
                ('load_post_commute', models.DecimalField(decimal_places=2, default=0.0, help_text='Load post commute for day n', max_digits=20)),
                ('acute_load_post_commute', models.DecimalField(decimal_places=2, default=0.0, help_text='Acute Load post commute for day n', max_digits=20)),
                ('zone_focus', models.IntegerField(default=0)),
                ('commute_pss_day', models.DecimalField(decimal_places=2, default=0.0, help_text='commute pss of a user in day', max_digits=20)),
                ('day_code', models.UUIDField(editable=False, help_text='Unique day code for each day', null=True)),
                ('week_code', models.UUIDField(editable=False, help_text='Unique week code for each week', null=True)),
                ('user_auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_days', to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'Planned Day Table',
                'db_table': 'planned_day',
            },
        ),
        migrations.CreateModel(
            name='ActualDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('activity_date', models.DateField()),
                ('actual_load', models.DecimalField(decimal_places=2, default=0.0, help_text='actual load of a user in day', max_digits=20)),
                ('actual_acute_load', models.DecimalField(decimal_places=2, default=0.0, help_text='actual acute load of a user in day', max_digits=20)),
                ('actual_pss', models.DecimalField(decimal_places=2, default=0.0, help_text='actual pss of a user in day', max_digits=20)),
                ('zone_focus', models.IntegerField(default=0)),
                ('recovery_index', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('prs_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('sqs_today', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('day_code', models.UUIDField(editable=False, help_text='Unique day code for each day', null=True)),
                ('week_code', models.UUIDField(editable=False, help_text='Unique week code for each week', null=True)),
                ('user_auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_days', to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'Actual Day Table',
                'db_table': 'actual_day',
            },
        ),
    ]
