# Generated by Django 3.0 on 2020-11-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0036_actualday_plannedday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualday',
            name='prs_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='actualday',
            name='recovery_index',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='actualday',
            name='sqs_today',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='actualday',
            name='zone_focus',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
