# Generated by Django 3.0 on 2021-05-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0038_auto_20210108_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualday',
            name='reason',
            field=models.TextField(help_text='The reason of a specific actual day row being created', null=True),
        ),
    ]
