# Generated by Django 3.0 on 2021-06-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0039_actualday_reason'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actualday',
            constraint=models.UniqueConstraint(condition=models.Q(is_active=True), fields=('day_code',), name='unique_active_code'),
        ),
    ]
