# Generated by Django 3.2.5 on 2021-10-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0041_auto_20210628_0618'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actualday',
            name='unique_active_code',
        ),
        migrations.AddConstraint(
            model_name='actualday',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user_auth_id', 'activity_date'), name='unique_active_activity_date'),
        ),
    ]
