# Generated by Django 3.2.5 on 2021-11-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0042_auto_20211029_0937'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actualday',
            name='unique_active_activity_date',
        ),
    ]
