# Generated by Django 3.0 on 2020-08-18 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0014_auto_20200818_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=55, null=True)),
                ('file_type', models.CharField(blank=True, help_text='Type of The Fit File', max_length=55, null=True)),
                ('activity_id', models.CharField(blank=True, help_text='Id of the activity file', max_length=255, null=True)),
                ('activity_type', models.CharField(blank=True, help_text='Type of the Activity', max_length=55, null=True)),
                ('activity_sub_type', models.CharField(blank=True, help_text='Sub Type of the Activity', max_length=55, null=True)),
                ('second_by_second_power', models.TextField(blank=True, help_text='Activity Fit File Second by Second Power data', null=True)),
                ('second_by_second_hr', models.TextField(blank=True, help_text='Activity Fit File Second by Second heart rate data', null=True)),
                ('second_by_second_speed', models.TextField(blank=True, help_text='Activity Fit File Second by Second heart rate data', null=True)),
                ('second_by_second_cadence', models.TextField(blank=True, help_text='Activity Fit File Second by Second Cadence data', null=True)),
                ('moving_time_in_seconds', models.IntegerField(default=0, help_text='Time where speed is 0 and power is 0')),
                ('elapsed_time_in_seconds', models.IntegerField(default=0, help_text='Time where speed is 0 and power is 0')),
                ('actual_time_in_power_zone', models.TextField(blank=True, help_text='Actual Time in zones in power data', null=True)),
                ('actual_time_in_hr_zone', models.TextField(blank=True, help_text='Actual Time in zones in heart rate data', null=True)),
                ('total_power', models.DecimalField(decimal_places=2, default=0.0, help_text='total power during activity', max_digits=20)),
                ('total_heart_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='total heart rate during activity', max_digits=20)),
                ('total_distance_in_meter', models.DecimalField(decimal_places=2, default=0.0, help_text='total distance covered during activity', max_digits=20)),
                ('moving_fraction', models.DecimalField(decimal_places=2, default=0.0, help_text='moving fraction of an activity', max_digits=20)),
                ('ride_summary', models.TextField(blank=True, help_text='User ride Summary', null=True)),
                ('weighted_power', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_strava_data', to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'Strava Data',
                'db_table': 'strava_data',
            },
        ),
    ]
