# Generated by Django 3.0 on 2020-09-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravadata',
            name='second_by_second_distance',
            field=models.TextField(blank=True, help_text='Activity Fit File Second by Second Distance data', null=True),
        ),
        migrations.AddField(
            model_name='stravadata',
            name='second_by_second_elevation',
            field=models.TextField(blank=True, help_text='Activity Fit File Second by Second Elevation data', null=True),
        ),
        migrations.AddField(
            model_name='stravadata',
            name='second_by_second_latitude',
            field=models.TextField(blank=True, help_text='Activity Fit File Second by Second Latitude data', null=True),
        ),
        migrations.AddField(
            model_name='stravadata',
            name='second_by_second_longitude',
            field=models.TextField(blank=True, help_text='Activity Fit File Second by Second Longitude data', null=True),
        ),
        migrations.AddField(
            model_name='stravadata',
            name='second_by_second_temperature',
            field=models.TextField(blank=True, help_text='Activity Fit File Second by Second Temperature data', null=True),
        ),
    ]
