# Generated by Django 3.0 on 2021-06-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0007_auto_20201021_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravadata',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
    ]
