# Generated by Django 3.2.5 on 2021-12-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0090_auto_20211207_0706'),
        ('strava', '0008_stravadata_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StravaData',
        ),
    ]
