# Generated by Django 3.0 on 2021-02-05 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0021_auto_20201019_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Record Type e.g. Longest Ride', max_length=55, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Record Type',
                'db_table': 'record_type',
            },
        ),
        migrations.CreateModel(
            name='RecordLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Indicates specific level of a particular record type')),
                ('required_value', models.DecimalField(decimal_places=2, help_text='Required threshold value for achieving a level', max_digits=20)),
                ('unit', models.CharField(help_text='Unit of the required value to achieve a level', max_length=25, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_levels', to='achievements.RecordType')),
            ],
            options={
                'verbose_name': 'Record Level',
                'db_table': 'record_level',
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('actual_session_code', models.UUIDField(editable=False, help_text='Needed for referring to the corresponding actual session')),
                ('record_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='achievements.RecordLevel')),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='achievements.RecordType')),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'Personal Record',
                'db_table': 'personal_record',
            },
        ),
    ]
