# Generated by Django 3.0 on 2020-02-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_focus', models.IntegerField()),
                ('priority_ranking', models.IntegerField()),
                ('zone_name', models.CharField(max_length=55)),
                ('power_lower_bound', models.IntegerField()),
                ('power_upper_bound', models.IntegerField()),
                ('heart_rate_lower_bound', models.IntegerField()),
                ('heart_rate_upper_bound', models.IntegerField()),
                ('rpe_lower_bound', models.IntegerField()),
                ('rpe_upper_bound', models.IntegerField()),
                ('associated_power_curve', models.IntegerField()),
                ('is_active', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'verbose_name': 'Training Zone Table',
                'db_table': 'training_zone',
            },
        ),
    ]
