# Generated by Django 3.0 on 2020-02-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_zone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingzone',
            name='associated_power_curve',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingzone',
            name='heart_rate_lower_bound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingzone',
            name='heart_rate_upper_bound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingzone',
            name='power_lower_bound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingzone',
            name='power_upper_bound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingzone',
            name='priority_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingzone',
            name='rpe_lower_bound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingzone',
            name='rpe_upper_bound',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
