# Generated by Django 3.0 on 2020-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_auto_20200326_2255'),
        ('block', '0004_auto_20200326_2255'),
        ('training_zone', '0002_auto_20200205_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingZoneTruthTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField()),
                ('zone_name', models.CharField(max_length=55, null=True)),
                ('zone_description', models.CharField(max_length=255, null=True)),
                ('zone_basic_adaptations_description', models.CharField(max_length=255, null=True)),
                ('zone_physiological_adaptations_description', models.CharField(max_length=255, null=True)),
                ('power_ftp_lower_bound', models.IntegerField(blank=True, null=True)),
                ('power_ftp_upper_bound', models.IntegerField(blank=True, null=True)),
                ('heart_rate_fthr_lower_bound', models.IntegerField(blank=True, null=True)),
                ('heart_rate_fthr_upper_bound', models.IntegerField(blank=True, null=True)),
                ('rpe_lower_bound', models.IntegerField(blank=True, null=True)),
                ('rpe_upper_bound', models.IntegerField(blank=True, null=True)),
                ('associated_power_curve', models.FloatField(blank=True, null=True)),
                ('is_active', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'verbose_name': 'Training Zone Truth Table',
                'db_table': 'training_zone_truth_table',
            },
        ),
        migrations.DeleteModel(
            name='TrainingZone',
        ),
    ]
