# Generated by Django 3.0 on 2020-04-04 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_zone', '0003_auto_20200326_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingzonetruthtable',
            options={'verbose_name': 'Training Zone TT'},
        ),
        migrations.AddField(
            model_name='trainingzonetruthtable',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingzonetruthtable',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainingzonetruthtable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='trainingzonetruthtable',
            table='training_zone',
        ),
    ]
