# Generated by Django 3.0 on 2020-04-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_zone', '0004_auto_20200404_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingzonetruthtable',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainingzonetruthtable',
            name='updated_at',
        ),
    ]
