# Generated by Django 3.0 on 2020-04-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_zone', '0005_auto_20200404_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingzonetruthtable',
            old_name='zone',
            new_name='zone_focus',
        ),
    ]
