# Generated by Django 3.0 on 2020-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_zone', '0006_auto_20200405_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingzonetruthtable',
            name='associated_power_curve',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
