# Generated by Django 3.0 on 2020-04-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_zone', '0007_auto_20200419_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingzonetruthtable',
            name='heart_rate_fthr_lower_bound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingzonetruthtable',
            name='heart_rate_fthr_upper_bound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingzonetruthtable',
            name='power_ftp_lower_bound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingzonetruthtable',
            name='power_ftp_upper_bound',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
