# Generated by Django 3.0 on 2020-11-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_zone', '0008_auto_20200501_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingzonetruthtable',
            name='max_heart_rate_lower_bound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingzonetruthtable',
            name='max_heart_rate_upper_bound',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
