# Generated by Django 3.0 on 2020-05-09 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0006_schedule_profile_data_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarminData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=55, null=True)),
                ('file_type', models.CharField(blank=True, help_text='Type of The Fit File', max_length=55, null=True)),
                ('activity_file_id', models.CharField(blank=True, help_text='Id of the activity file', max_length=255, null=True)),
                ('activity_type', models.CharField(blank=True, help_text='Type of the Activity', max_length=55, null=True)),
                ('activity_sub_type', models.CharField(blank=True, help_text='Sub Type of the Activity', max_length=55, null=True)),
                ('second_power_data', models.TextField(blank=True, help_text='Activity Fit File Second by Second Power data', null=True)),
                ('second_hr_data', models.TextField(blank=True, help_text='Activity Fit File Second by Second herat rate data', null=True)),
                ('total_time_in_seconds', models.IntegerField(default=0, help_text='Total activity time in seconds')),
                ('total_distance_in_meter', models.DecimalField(decimal_places=2, default=0.0, help_text='total distance covered during activity', max_digits=20)),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_garmin_data', to='user_auth.UserAuthModel')),
            ],
        ),
    ]
