# Generated by Django 3.0 on 2020-05-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmindata',
            name='total_heart_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='total heart rate during activity', max_digits=20),
        ),
        migrations.AddField(
            model_name='garmindata',
            name='total_power',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='total power during activity', max_digits=20),
        ),
    ]
