# Generated by Django 3.0 on 2020-05-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0003_auto_20200522_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmindata',
            name='actual_time_in_hr_zone',
            field=models.TextField(blank=True, help_text='Actual Time in zones in heart rate data', null=True),
        ),
        migrations.AddField(
            model_name='garmindata',
            name='actual_time_in_power_zone',
            field=models.TextField(blank=True, help_text='Actual Time in zones in power data', null=True),
        ),
        migrations.AlterField(
            model_name='garmindata',
            name='second_hr_data',
            field=models.TextField(blank=True, help_text='Activity Fit File Second by Second heart rate data', null=True),
        ),
    ]
