# Generated by Django 3.0 on 2020-06-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0004_auto_20200527_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garmindata',
            options={'verbose_name': 'Garmin Data'},
        ),
        migrations.AlterModelTable(
            name='garmindata',
            table='garmin_data',
        ),
    ]
