# Generated by Django 3.0 on 2020-08-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0007_garmindata_moving_fraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmindata',
            name='activity_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garmindata',
            name='elevation_gain',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='elevation gain during an activity', max_digits=20),
        ),
    ]
