# Generated by Django 3.0 on 2020-08-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0007_garmindata_moving_fraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmindata',
            name='second_by_second_cadence',
            field=models.TextField(blank=True, help_text='Activity Fit File Second by Second Cadence data', null=True),
        ),
    ]
