# Generated by Django 3.0 on 2020-08-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0008_garmindata_second_by_second_cadence'),
        ('garmin', '0008_auto_20200814_0339'),
    ]

    operations = [
    ]
