# Generated by Django 3.0 on 2020-08-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0009_auto_20200811_1622'),
        ('garmin', '0009_merge_20200819_1839'),
    ]

    operations = [
    ]
