# Generated by Django 3.0 on 2020-08-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0010_merge_20200819_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmindata',
            name='manufacturer',
            field=models.CharField(help_text='Manufacturer of the Fit File', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='garmindata',
            name='elapsed_time_in_seconds',
            field=models.IntegerField(default=0, help_text='Total time of the activity'),
        ),
        migrations.AlterField(
            model_name='garmindata',
            name='moving_time_in_seconds',
            field=models.IntegerField(default=0, help_text='Time where speed is not 0 and power is not 0'),
        ),
    ]
