# Generated by Django 3.0 on 2020-09-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0011_auto_20200827_0123'),
        ('garmin', '0011_auto_20200830_1327'),
    ]

    operations = [
    ]
