# Generated by Django 3.0 on 2020-09-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0012_merge_20200904_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmindata',
            name='second_by_second_time',
            field=models.TextField(blank=True, help_text='Activity Fit File Second by Second elapsed time in seconds                                                          from start of the activity', null=True),
        ),
    ]
