# Generated by Django 3.0 on 2020-10-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0013_garmindata_second_by_second_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmindata',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
