# Generated by Django 3.0 on 2020-10-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0015_auto_20201021_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmindata',
            name='elevation_gain',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Elevation gain during an activity', max_digits=20),
        ),
        migrations.AlterField(
            model_name='garmindata',
            name='file_type',
            field=models.CharField(blank=True, help_text='Type of The File', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='garmindata',
            name='moving_fraction',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Moving fraction of an activity', max_digits=20),
        ),
        migrations.AlterField(
            model_name='garmindata',
            name='second_by_second_time',
            field=models.TextField(blank=True, help_text='Second by Second elapsed time in seconds from start of the activity', null=True),
        ),
        migrations.AlterField(
            model_name='garmindata',
            name='total_distance_in_meter',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total distance covered during activity', max_digits=20),
        ),
        migrations.AlterField(
            model_name='garmindata',
            name='total_heart_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total heart rate during activity', max_digits=20),
        ),
        migrations.AlterField(
            model_name='garmindata',
            name='total_power',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total power during activity', max_digits=20),
        ),
    ]
