# Generated by Django 3.0 on 2020-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0016_auto_20201021_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garmindata',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='garmindata',
            name='third_party_ride_summary',
        ),
        migrations.AddField(
            model_name='garmindata',
            name='flagged_values',
            field=models.TextField(blank=True, help_text='The values which are flagged', null=True),
        ),
    ]
