# Generated by Django 3.0 on 2020-11-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0021_auto_20201019_1708'),
        ('garmin', '0017_auto_20201021_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurveCalculationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('ride_data_id', models.IntegerField()),
                ('source', models.PositiveSmallIntegerField(choices=[(1, 'Garmin'), (2, 'Strava'), (3, 'Wahoo')])),
                ('power_curve', models.TextField(blank=True, null=True)),
                ('heart_rate_curve', models.TextField(blank=True, null=True)),
                ('user_auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curve_data', to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'Curve Calculation Data',
                'db_table': 'curve_calculation_data',
            },
        ),
    ]
