# Generated by Django 3.0 on 2020-11-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0018_curvecalculationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curvecalculationdata',
            name='heart_rate_curve',
            field=models.TextField(blank=True, help_text='Stores hr curve array as string', null=True),
        ),
        migrations.AlterField(
            model_name='curvecalculationdata',
            name='power_curve',
            field=models.TextField(blank=True, help_text='Stores power curve array as string', null=True),
        ),
        migrations.AlterField(
            model_name='curvecalculationdata',
            name='ride_data_id',
            field=models.IntegerField(help_text='Stores related GarminData / StravaData ID based on source'),
        ),
        migrations.AlterField(
            model_name='curvecalculationdata',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Garmin'), (2, 'Strava'), (3, 'Wahoo')], help_text='Stores source of the activity'),
        ),
    ]
