# Generated by Django 3.0 on 2020-12-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0019_auto_20201119_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curvecalculationdata',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Garmin'), (2, 'Strava'), (3, 'Wahoo'), (10, 'Manual')], help_text='Stores source of the activity'),
        ),
    ]
