# Generated by Django 3.0 on 2020-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0020_auto_20201204_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curvecalculationdata',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Garmin'), (2, 'Strava'), (3, 'Wahoo'), (4, 'Manual')], help_text='Stores source of the activity'),
        ),
    ]
