# Generated by Django 3.0 on 2021-03-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0021_auto_20201204_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='curvecalculationdata',
            name='activity_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
