# Generated by Django 3.0 on 2021-03-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0022_curvecalculationdata_activity_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='curvecalculationdata',
            name='activity_type',
            field=models.CharField(help_text='Type of the Activity', max_length=55, null=True),
        ),
    ]
