# Generated by Django 3.0 on 2021-06-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0024_auto_20210328_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='curvecalculationdata',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='garmindata',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
    ]
