# Generated by Django 3.2.5 on 2021-12-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0090_auto_20211207_0706'),
        ('garmin', '0025_auto_20210628_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curvecalculationdata',
            name='ride_data_id',
        ),
        migrations.DeleteModel(
            name='GarminData',
        ),
    ]
