# Generated by Django 3.0 on 2020-12-04 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0021_auto_20201019_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='My Ride', max_length=255)),
                ('type', models.CharField(blank=True, help_text='Type of the Activity', max_length=55, null=True)),
                ('label', models.CharField(blank=True, help_text='Type of the Activity', max_length=55, null=True)),
                ('elapsed_time_in_seconds', models.IntegerField(default=0, help_text='Total time of the activity')),
                ('average_power', models.IntegerField(default=0, help_text='Average power during activity')),
                ('average_heart_rate', models.IntegerField(default=0, help_text='Average heart rate during activity')),
                ('total_distance_in_meter', models.DecimalField(decimal_places=2, default=0.0, help_text='Total distance covered during activity', max_digits=20)),
                ('stress_level', models.IntegerField(help_text='How hard or stressful the activity was for the athlete')),
                ('activity_description', models.TextField(blank=True, help_text="User's description of the activity", max_length=250, null=True)),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillar_data', to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'Pillar Data',
                'db_table': 'pillar_data',
            },
        ),
    ]
