# Generated by Django 3.0 on 2020-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='elapsed_time_in_seconds',
            new_name='moving_time_in_seconds',
        ),
        migrations.AddField(
            model_name='activity',
            name='sub_type',
            field=models.CharField(blank=True, help_text='Sub Type of the Activity', max_length=55, null=True),
        ),
    ]
