# Generated by Django 3.0 on 2020-12-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillar', '0002_auto_20201204_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='average_speed',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average speed during activity', max_digits=20),
        ),
    ]
