# Generated by Django 3.0 on 2020-12-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillar', '0003_activity_average_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='average_speed',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average speed during activity in Km/h', max_digits=20),
        ),
    ]
