# Generated by Django 3.0 on 2020-12-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillar', '0004_auto_20201210_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='average_heart_rate',
            field=models.IntegerField(blank=True, default=0, help_text='Average heart rate during activity', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='average_power',
            field=models.IntegerField(blank=True, default=0, help_text='Average power during activity', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='stress_level',
            field=models.IntegerField(blank=True, help_text='How hard or stressful the activity was for the athlete', null=True),
        ),
    ]
