# Generated by Django 3.0 on 2021-03-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pillar', '0008_auto_20210302_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='sub_type',
            new_name='activity_sub_type',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='type',
            new_name='activity_type',
        ),
    ]
