# Generated by Django 3.0 on 2021-07-06 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('purpose', models.CharField(blank=True, help_text='Purpose or the outcome of a specific package', max_length=105)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, help_text='Duration of the training package in text format', max_length=55)),
                ('title_image_url', models.TextField(blank=True, help_text='Training package title image url', null=True)),
                ('description_image_url', models.TextField(blank=True, help_text='Training package description image url', null=True)),
                ('share_link', models.TextField(blank=True, help_text='Training package share url', null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'package',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('purpose', models.CharField(blank=True, help_text='Purpose or the outcome of a specific package', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(help_text='Duration of the sub package in days')),
                ('icon_url', models.TextField(blank=True, help_text='Training package icon url', null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_packages', to='packages.Package')),
            ],
            options={
                'db_table': 'sub_package',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user_id', models.UUIDField()),
                ('sub_package', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_packages', to='packages.SubPackage')),
            ],
            options={
                'db_table': 'user_package',
                'ordering': ['id'],
            },
        ),
    ]
