# Generated by Django 3.2.5 on 2021-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_subpackage_week_zone_focuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('PERFORMANCE', 'Performance'), ('LIFESTYLE', 'Lifestyle')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='subpackage',
            name='multiple_duration',
            field=models.BooleanField(default=False, verbose_name='Multiple duration'),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration of the training package in text format', max_length=55, null=True),
        ),
    ]
