# Generated by Django 3.2.5 on 2021-09-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20210903_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_type',
            new_name='goal_type',
        ),
    ]
