# Generated by Django 3.2.5 on 2021-09-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_alter_subpackage_week_zone_focuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='caption',
            field=models.TextField(blank=True, help_text='For package sub package page caption'),
        ),
    ]
