# Generated by Django 3.2.5 on 2021-10-21 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_auto_20210707_0529'),
        ('packages', '0007_package_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('week_no', models.IntegerField(help_text='The week no. when this hub will be shown')),
                ('content_url', models.TextField(help_text='URL for the main content of knowledge hub')),
                ('calendar_text', models.TextField(help_text='calendar tile text of knowledge hub')),
                ('notification_text', models.TextField(help_text='notification text of knowledge hub')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'knowledge_hub',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='goal_detail_knowledge_hub_text',
            field=models.TextField(blank=True, help_text='Goal detail page knowledge hub page text', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='knowledge_hub_text',
            field=models.TextField(blank=True, help_text='Base knowledge hub page text', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='knowledge_hub_title',
            field=models.TextField(blank=True, help_text='Base knowledge hub page title', null=True),
        ),
        migrations.CreateModel(
            name='UserKnowledgeHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user_id', models.UUIDField()),
                ('activation_date', models.DateField(help_text='The first date of the week with which this knowledge hub entry is associated with e.g when user willreceive notification for this knowledge hub entry (weekly basis)')),
                ('knowledge_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_knowledge_hub', to='packages.knowledgehub')),
                ('user_plan', models.ForeignKey(help_text='Plan related to this user knowledge hub entry', on_delete=django.db.models.deletion.CASCADE, related_name='user_knowledge_hub', to='plan.userplan')),
            ],
            options={
                'db_table': 'user_knowledge_hub',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='knowledgehub',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_hub', to='packages.package'),
        ),
    ]
