# Generated by Django 3.0 on 2020-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettingsqueue',
            name='task_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', help_text='indicates if this task is completed or not from the queue', max_length=255, null=True),
        ),
    ]
