# Generated by Django 3.0 on 2020-07-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20200725_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettingsqueue',
            name='task_status',
            field=models.CharField(blank=True, choices=[(1, 'Pending'), (2, 'Completed')], default=1, help_text='indicates if this task is completed or not from the queue', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersettingsqueue',
            name='type',
            field=models.CharField(blank=True, choices=[(1, 'System settings'), (2, 'User settings')], default=1, help_text='settings type may be of system settings or user settings', max_length=255, null=True),
        ),
    ]
