# Generated by Django 3.0 on 2020-07-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20200725_1936'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usersettings',
            index=models.Index(fields=['code'], name='settings_us_code_a40a64_idx'),
        ),
        migrations.AddIndex(
            model_name='usersettingsqueue',
            index=models.Index(fields=['code'], name='settings_us_code_6daf9f_idx'),
        ),
    ]
