# Generated by Django 3.0 on 2020-07-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20200725_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='type',
            field=models.CharField(blank=True, choices=[(1, 'System settings'), (2, 'User settings')], default=1, help_text='settings type may be of system settings or user settings', max_length=255, null=True),
        ),
    ]
