# Generated by Django 3.0 on 2020-08-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20200725_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Third Party Service Name', max_length=55, unique=True)),
                ('priority', models.PositiveSmallIntegerField(help_text='Lower Priority will get Higher Precedence', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Third Party Service Settings',
                'db_table': 'third_party_settings',
            },
        ),
    ]
