# Generated by Django 3.0 on 2020-08-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_thirdpartysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartysettings',
            name='code',
            field=models.IntegerField(choices=[(1, 'Garmin'), (2, 'Strava'), (3, 'Wahoo')], null=True),
        ),
    ]
