# Generated by Django 3.0 on 2020-10-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_thirdpartysettings_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='updated_by',
            field=models.CharField(blank=True, help_text='by whom this settings value is updated', max_length=255, null=True),
        ),
    ]
