# Generated by Django 3.0 on 2020-12-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20201019_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartysettings',
            name='code',
            field=models.IntegerField(choices=[(1, 'Garmin'), (2, 'Strava'), (3, 'Wahoo'), (10, 'Manual')], null=True),
        ),
    ]
