# Generated by Django 3.0 on 2021-02-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_auto_20201204_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdpartysettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='thirdpartysettings',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='usersettingsqueue',
            name='updated_by',
            field=models.CharField(blank=True, help_text='by whom this settings value is updated', max_length=255, null=True),
        ),
    ]
