# Generated by Django 3.0 on 2021-03-09 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20210209_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
