# Generated by Django 3.2.5 on 2022-02-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_auto_20210628_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='user_auth',
        ),
    ]
