# Generated by Django 3.2.5 on 2022-02-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_remove_usersettings_user_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettingsqueue',
            name='user_auth',
        ),
    ]
