# Generated by Django 3.0 on 2020-02-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'verbose_name': 'Block Table',
                'db_table': 'block',
            },
        ),
    ]
