# Generated by Django 3.0 on 2020-02-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('block', '0001_initial'),
        ('plan', '0001_initial'),
        ('training_zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Plan'),
        ),
        migrations.AddField(
            model_name='block',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_zone.TrainingZone'),
        ),
    ]
