# Generated by Django 3.0 on 2020-03-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20200307_1514'),
        ('block', '0002_auto_20200205_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='actual_atl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='actual_ctl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='actual_pss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='actual_tsb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='no_of_weeks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='target_atl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='target_ctl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='target_pss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='target_tsb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Plan'),
        ),
        migrations.AlterModelTable(
            name='block',
            table='user_block_plan',
        ),
    ]
