# Generated by Django 3.0 on 2020-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_auto_20200310_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='zone',
        ),
        migrations.AddField(
            model_name='block',
            name='time_in_Z0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='time_in_Z1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='time_in_Z2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='time_in_Z3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='time_in_Z4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='time_in_Z5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='time_in_Z6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='time_in_Z7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='zone_focus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
