# Generated by Django 3.0 on 2020-03-27 13:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('block', '0004_auto_20200326_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='plan',
        ),
        migrations.AddField(
            model_name='block',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='block',
            name='number',
            field=models.IntegerField(blank=True, help_text='block number', null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='user',
            field=models.ForeignKey(default=1, help_text='user of this block', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='user_auth.UserAuthModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='zone_focus',
            field=models.FloatField(blank=True, default=0.0, help_text='zone focus value for this block', null=True),
        ),
    ]
