# Generated by Django 3.0 on 2020-03-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_auto_20200326_2255'),
        ('week', '0004_auto_20200327_1322'),
        ('session', '0009_auto_20200326_2255'),
        ('user_auth', '0001_initial'),
        ('block', '0005_auto_20200327_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Block',
            new_name='UserBlock',
        ),
    ]
