# Generated by Django 3.0 on 2020-03-28 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20200326_2255'),
        ('block', '0008_auto_20200327_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblock',
            name='end_date',
            field=models.DateField(blank=True, help_text='end date of this block', null=True),
        ),
        migrations.AddField(
            model_name='userblock',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Plan'),
        ),
        migrations.AddField(
            model_name='userblock',
            name='start_date',
            field=models.DateField(blank=True, help_text='start date of this block', null=True),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='no_of_weeks',
            field=models.IntegerField(blank=True, help_text='total number of weeks for this block', null=True),
        ),
    ]
