# Generated by Django 3.0 on 2020-03-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20200326_2255'),
        ('block', '0009_auto_20200328_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblock',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Plan'),
        ),
    ]
