# Generated by Django 3.0 on 2020-03-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20200327_1810'),
        ('block', '0010_auto_20200328_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblock',
            name='event',
            field=models.ForeignKey(blank=True, help_text='event of this block', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='event.UserEvent'),
        ),
    ]
