# Generated by Django 3.0 on 2020-03-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0011_userblock_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userblock',
            old_name='event',
            new_name='user_event',
        ),
    ]
