# Generated by Django 3.0 on 2020-03-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20200326_2255'),
        ('block', '0012_auto_20200328_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblock',
            name='user_event',
        ),
        migrations.AlterField(
            model_name='userblock',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='plan of this block', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='plan.Plan'),
        ),
    ]
