# Generated by Django 3.0 on 2020-03-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0013_auto_20200328_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userblock',
            old_name='plan',
            new_name='user_plan',
        ),
    ]
