# Generated by Django 3.0 on 2020-03-31 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0014_auto_20200328_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userblock',
            options={'verbose_name': 'User Block Table'},
        ),
        migrations.AlterModelTable(
            name='userblock',
            table='user_block',
        ),
    ]
