# Generated by Django 3.0 on 2020-03-31 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0016_auto_20200331_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userblock',
            options={'verbose_name': 'User Block Table'},
        ),
        migrations.AlterModelTable(
            name='userblock',
            table='user_block',
        ),
    ]
