# Generated by Django 3.0 on 2020-04-02 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_auto_20200331_1854'),
        ('user_auth', '0002_auto_20200330_0016'),
        ('block', '0017_auto_20200331_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userblock',
            old_name='actual_atl',
            new_name='actual_acute_load',
        ),
        migrations.RenameField(
            model_name='userblock',
            old_name='actual_ctl',
            new_name='actual_freshness',
        ),
        migrations.RenameField(
            model_name='userblock',
            old_name='actual_tsb',
            new_name='actual_load',
        ),
        migrations.RenameField(
            model_name='userblock',
            old_name='target_atl',
            new_name='target_acute_load',
        ),
        migrations.RenameField(
            model_name='userblock',
            old_name='target_ctl',
            new_name='target_freshness',
        ),
        migrations.RenameField(
            model_name='userblock',
            old_name='target_tsb',
            new_name='target_load',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='user',
        ),
        migrations.AddField(
            model_name='userblock',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userblock',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userblock',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userblock',
            name='user_auth',
            field=models.ForeignKey(default=1, help_text='User of this block', on_delete=django.db.models.deletion.CASCADE, related_name='user_blocks', to='user_auth.UserAuthModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userblock',
            name='user_plan',
            field=models.ForeignKey(blank=True, help_text='plan of this block', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_blocks', to='plan.UserPlan'),
        ),
    ]
