# Generated by Django 3.0 on 2020-04-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0019_auto_20200405_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblock',
            name='no_of_weeks',
            field=models.IntegerField(default=4, help_text='total number of weeks for this block'),
            preserve_default=False,
        ),
    ]
