# Generated by Django 3.0 on 2020-04-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0021_auto_20200410_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblock',
            name='target_pss',
        ),
        migrations.AddField(
            model_name='userblock',
            name='planned_pss',
            field=models.FloatField(blank=True, default=0.0, help_text='planned pss of this block', null=True),
        ),
    ]
