# Generated by Django 3.0 on 2020-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0022_auto_20200416_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblock',
            name='actual_acute_load',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='actual acute load of a user in block', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='actual_freshness',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='actual freshness of a user in a block', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='actual_load',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='actual load of a user in block', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='actual_pss',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='actual pss of a user in block', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='planned_pss',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='planned pss of this block', max_digits=20),
        ),
    ]
