# Generated by Django 3.0 on 2020-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0023_auto_20200419_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblock',
            name='time_in_Z0',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='time_in_Z1',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='time_in_Z2',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='time_in_Z3',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='time_in_Z4',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='time_in_Z5',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='time_in_Z6',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='time_in_Z7',
        ),
        migrations.AddField(
            model_name='userblock',
            name='actual_time_in_zones',
            field=models.TextField(blank=True, help_text='User actual time in zone 0-7', null=True),
        ),
        migrations.AddField(
            model_name='userblock',
            name='planned_time_in_zones',
            field=models.TextField(blank=True, help_text='User planned time in zone 0-7', null=True),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='target_acute_load',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='target_freshness',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='target_load',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
