# Generated by Django 3.0 on 2020-10-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0024_auto_20200419_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblock',
            name='block_code',
            field=models.UUIDField(editable=False, help_text='Unique block code for each block', null=True),
        ),
        migrations.AddField(
            model_name='userblock',
            name='plan_code',
            field=models.UUIDField(editable=False, help_text='Week under the plan', null=True),
        ),
    ]
