# Generated by Django 3.0 on 2021-07-07 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0023_remove_userauthmodel_user_id'),
        ('block', '0026_userblock_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblock',
            name='user_auth',
            field=models.ForeignKey(help_text='User of this block', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_blocks', to='user_auth.UserAuthModel'),
        ),
    ]
