# Generated by Django 3.0 on 2021-02-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_rolepermission_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
