# Generated by Django 3.0 on 2021-02-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_delete_userrole'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserOrganization',
            new_name='Organization',
        ),
    ]
