# Generated by Django 3.0 on 2021-02-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20210223_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RolePermission',
            new_name='OrganizationRolePermission',
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization'},
        ),
        migrations.AlterModelOptions(
            name='organizationrolepermission',
            options={'verbose_name': 'Organization Role Permission'},
        ),
    ]
