# Generated by Django 3.0 on 2021-02-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20210223_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationRolePermission',
            new_name='OrganizationRolePermissionMap',
        ),
        migrations.AlterModelOptions(
            name='organizationrolepermissionmap',
            options={'verbose_name': 'Organization Role Permission Map'},
        ),
        migrations.AlterModelOptions(
            name='permissionactivity',
            options={'verbose_name': 'Activity Permission Map', 'verbose_name_plural': 'Activity Permission Map'},
        ),
        migrations.AlterModelOptions(
            name='userorganizationrolemap',
            options={'verbose_name': 'User Organization Role Map'},
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organization',
        ),
        migrations.AlterModelTable(
            name='organizationrolepermissionmap',
            table='organization_role_permission',
        ),
    ]
