# Generated by Django 3.0 on 2021-02-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20210223_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionactivity',
            options={'verbose_name': 'Activity Permission Map', 'verbose_name_plural': 'Activity Permission Maps'},
        ),
    ]
