# Generated by Django 3.0 on 2020-07-11 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0006_schedule_profile_data_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronHistoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_code', models.PositiveSmallIntegerField(choices=[(1, 'Midnight Calculation'), (2, 'Morning Calculation'), (3, 'Auto Update Training Plan')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Successful'), (2, 'Failed')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.UserAuthModel')),
            ],
        ),
    ]
