# Generated by Django 3.0 on 2020-07-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200711_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronhistorylog',
            name='cron_code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Midnight Calculation'), (2, 'Morning Calculation'), (3, 'Auto Update Training Plan'), (4, 'Update User Settings')]),
        ),
    ]
