# Generated by Django 3.0 on 2020-09-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200725_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronhistorylog',
            name='cron_code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Midnight Calculation'), (2, 'Morning Calculation'), (3, 'Auto Update Training Plan'), (4, 'Update User Settings'), (5, 'Update Today Notification For User')]),
        ),
    ]
