# Generated by Django 3.0 on 2021-06-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200926_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronhistorylog',
            old_name='user',
            new_name='user_auth',
        ),
    ]
