# Generated by Django 3.0 on 2021-06-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210628_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronhistorylog',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
    ]
