# Generated by Django 3.0 on 2020-07-14 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0006_schedule_profile_data_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of user notification', max_length=55)),
                ('message', models.CharField(help_text='Description of the notification', max_length=1000)),
                ('recipient_type', models.PositiveSmallIntegerField(choices=[(1, 'User Group'), (2, 'Individual'), (3, 'All')])),
                ('recipient_id', models.IntegerField(blank=True, null=True)),
                ('initiator_name', models.CharField(help_text='Name of the notification initiator e.g. cron, admin', max_length=55)),
                ('initiator_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Notification',
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_time', models.TimeField()),
                ('auto_closable', models.BooleanField(default=False)),
                ('auto_closable_time', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_auth', models.ForeignKey(help_text='User id', on_delete=django.db.models.deletion.CASCADE, to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'User Notification Setting',
                'db_table': 'user_notification_setting',
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the notification', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Type',
                'db_table': 'notification_type',
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(help_text='Notification expired date time')),
                ('action', models.PositiveIntegerField(choices=[(1, 'Initiated'), (2, 'Showed'), (3, 'Clicked'), (4, 'Swiped'), (5, 'Closed')])),
                ('notification', models.ForeignKey(help_text='Notification id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='notification.Notification')),
                ('receiver', models.ForeignKey(help_text='Notification receiver User id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'Notification History',
                'db_table': 'notification_history',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(help_text='Type of the notification e.g. Campaign, Plan Update', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.NotificationType'),
        ),
    ]
