# Generated by Django 3.0 on 2020-07-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_auto_20200714_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationsetting',
            name='user_auth',
        ),
    ]
