# Generated by Django 3.0 on 2020-07-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('notification', '0002_remove_usernotificationsetting_user_auth'),
    ]

    operations = [
    ]
