# Generated by Django 3.0 on 2020-07-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20200716_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationsetting',
            name='expired_time',
            field=models.TimeField(default='12:00:00.0000'),
        ),
    ]
