# Generated by Django 3.0 on 2020-09-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20200716_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notificationtype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notificationtype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='priority',
            field=models.IntegerField(default=9999999),
        ),
    ]
