# Generated by Django 3.0 on 2020-10-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20200926_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationsetting',
            name='expired_time',
            field=models.TimeField(default='23:59:59.0000'),
        ),
    ]
