# Generated by Django 3.0 on 2020-10-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_pushnotificationlog_pushnotificationsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationsetting',
            name='device_token',
            field=models.TextField(),
        ),
    ]
