# Generated by Django 3.0 on 2020-10-19 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0020_auto_20201005_1751'),
        ('notification', '0008_auto_20201010_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsetting',
            name='user_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting_temp', to='user_auth.UserAuthModel'),
        ),
    ]
