# Generated by Django 3.0 on 2020-10-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20201012_1751'),
        ('notification', '0008_auto_20201010_0950'),
    ]

    operations = [
    ]
