# Generated by Django 3.0 on 2020-10-20 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_auto_20201019_1715'),
        ('notification', '0009_merge_20201017_0614'),
    ]

    operations = [
    ]
