# Generated by Django 3.0 on 2021-02-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0015_auto_20210118_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.TextField(blank=True, help_text='Holds data related to the notification e.g. actual session code for over-training notification', null=True),
        ),
    ]
