# Generated by Django 3.0 on 2021-06-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0018_auto_20210628_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
    ]
