# Generated by Django 3.2.5 on 2021-08-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0019_notificationhistory_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationlog',
            name='user_actions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
