# Generated by Django 3.2.5 on 2022-02-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0021_auto_20211027_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotificationsetting',
            name='user_auth',
        ),
    ]
