# Generated by Django 3.2.5 on 2022-03-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0022_remove_pushnotificationsetting_user_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title of the notification', max_length=55)),
                ('body', models.CharField(help_text='description of the notification', max_length=1000)),
                ('data', models.TextField(blank=True, help_text='Holds data related to the notification e.g. actual session code for over-training notification', null=True)),
                ('action', models.PositiveIntegerField(choices=[(1, 'Initiated'), (2, 'Showed'), (3, 'Clicked'), (4, 'Swiped'), (5, 'Closed')], default=1)),
                ('receiver_id', models.UUIDField(editable=False, help_text='it referring to the user_id', null=True)),
                ('generated_by', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'In App Notification',
                'db_table': 'in_app_notification',
            },
        ),
    ]
