# Generated by Django 3.2.5 on 2022-03-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0023_inappnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
