# Generated by Django 3.2.5 on 2022-06-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0024_inappnotification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='data',
            field=models.JSONField(blank=True, help_text='Holds data related to the notification e.g. actual session code for over-training notification', null=True),
        ),
    ]
