# Generated by Django 3.0 on 2020-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('password', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('registration_type', models.IntegerField(default=1)),
                ('access_token', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('strava_user_token', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('strava_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('garmin_user_token', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('garmin_user_secret', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('garmin_user_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'User Authentication Table',
                'db_table': 'user_auth',
            },
        ),
    ]
