# Generated by Django 3.0 on 2020-03-29 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='user onboarding date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userauthmodel',
            name='updated_at',
            field=models.DateField(auto_now=True, help_text='user info updating date'),
        ),
    ]
