# Generated by Django 3.0 on 2020-05-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20200509_0044'),
    ]

    operations = [
        migrations.RunSQL(
            "update user_auth as ua set schedule_data_id = usd.id"
            " from user_schedule_data as usd"
            " where usd.user_auth_id = ua.id"
        ),
        migrations.RunSQL(
            "update user_auth as ua set profile_data_id = upd.id"
            " from user_profile as upd"
            " where upd.user_auth_id = ua.id"
        )
    ]
