# Generated by Django 3.0 on 2020-07-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('user_auth', '0006_schedule_profile_data_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthmodel',
            name='notification_setting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.UserNotificationSetting'),
        ),
    ]
