# Generated by Django 3.0 on 2020-07-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_userauthmodel_notification_setting'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO user_notification_setting (expired_time, auto_closable, auto_closable_time, created_at,"
            " updated_at, user_auth_id) SELECT '12:00:00', false, null, now(), now(), id FROM user_auth"
        )
    ]
