# Generated by Django 3.0 on 2020-07-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_auto_20200714_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthmodel',
            name='third_party_connections',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
