# Generated by Django 3.0 on 2020-08-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_auto_20200714_1549'),
    ]

    operations = [
        migrations.RunSQL(
        #    "delete from auth_user where username='cron';"
        #    "insert into auth_user (password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) "
        #    "values ('pbkdf2_sha256$180000$axvbLqoAUxHI$lVpFTUz3J84c9sXJIm0KRtZRIw/4XcecM0m78ywi1UA=', null, false, 'cron', '', '', '', false, true, now());"
            "select * from user_auth limit 1"
        )
    ]
