# Generated by Django 3.0 on 2020-08-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_auto_20200725_0952'),
        ('user_auth', '0010_auto_20200803_1839'),
    ]

    operations = [
    ]
