# Generated by Django 3.0 on 2020-08-31 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0040_availabletrainingdurationsinhour_commuteweek_usertrainingavailability'),
        ('user_auth', '0014_auto_20200818_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthmodel',
            name='training_availability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserTrainingAvailability'),
        ),
    ]
