# Generated by Django 3.0 on 2020-09-13 20:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0016_remove_userauthmodel_training_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(blank=True, default=510309, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('verifier_token', models.CharField(blank=True, default=uuid.UUID('54c4495a-e0ac-4954-968a-f93b2e66b519'), max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, default=uuid.UUID('0e9a876a-ef1e-4084-94fc-223d7c7f21e1'), max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True, help_text='otp creation date')),
                ('updated_at', models.DateField(auto_now=True, help_text='otp updating date')),
            ],
            options={
                'verbose_name': 'OTP Table',
                'db_table': 'otp',
            },
        ),
    ]
