# Generated by Django 3.0 on 2020-10-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0019_auto_20200915_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthmodel',
            name='access_token_expires_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userauthmodel',
            name='refresh_token_expires_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
