# Generated by Django 3.0 on 2020-10-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0020_auto_20201005_1751'),
        ('user_profile', '0052_auto_20201019_1427'),
        ('notification', '0010_auto_20201019_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthmodel',
            name='notification_setting',
        ),
        migrations.RemoveField(
            model_name='userauthmodel',
            name='personalise_data',
        ),
        migrations.RemoveField(
            model_name='userauthmodel',
            name='profile_data',
        ),
    ]
