# Generated by Django 3.0 on 2021-06-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0022_auto_20210628_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthmodel',
            name='user_id',
        ),
    ]
