# Generated by Django 3.0 on 2020-02-10 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sex',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unit',
            field=models.CharField(choices=[('M', 'Metric'), ('I', 'Imperial')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserScheduleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commute_to_work_by_bike', models.BooleanField()),
                ('duration_single_commute', models.TimeField(blank=True, max_length=50, null=True)),
                ('days_commute_by_bike', models.TextField()),
                ('available_training_hours_per_day_outside_commuting', models.TextField()),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'User Schedule Data Table',
                'db_table': 'user_schedule_data',
            },
        ),
        migrations.CreateModel(
            name='UserPersonalizeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('training_hours_over_last_4_weeks', models.TextField()),
                ('current_ftp', models.IntegerField()),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'User Personalize Data Table',
                'db_table': 'user_personalize_data',
            },
        ),
    ]
