# Generated by Django 3.0 on 2020-03-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalisedata',
            name='starting_prs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
