# Generated by Django 3.0 on 2020-02-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('user_profile', '0002_auto_20200210_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPersonalizeData',
            new_name='UserPersonaliseData',
        ),
        migrations.AlterModelOptions(
            name='userpersonalisedata',
            options={'verbose_name': 'User Personalise Data Table'},
        ),
        migrations.AlterModelTable(
            name='userpersonalisedata',
            table='user_personalise_data',
        ),
    ]
