# Generated by Django 3.0 on 2020-02-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200210_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalisedata',
            name='current_ftp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
