# Generated by Django 3.0 on 2020-02-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20200212_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalisedata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonalisedata',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
