# Generated by Django 3.0 on 2020-03-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userpersonalisedata_starting_prs'),
        ('user_profile', '0006_auto_20200314_0018'),
    ]

    operations = [
    ]
