# Generated by Django 3.0 on 2020-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_merge_20200326_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalisedata',
            name='starting_acute_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpersonalisedata',
            name='starting_load',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
