# Generated by Django 3.0 on 2020-03-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_merge_20200323_1822'),
        ('user_profile', '0008_auto_20200326_2255'),
    ]

    operations = [
    ]
