# Generated by Django 3.0 on 2020-03-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20200326_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalisedata',
            name='current_fthr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
