# Generated by Django 3.0 on 2020-03-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_userpersonalisedata_current_fthr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscheduledata',
            name='duration_single_commute',
        ),
        migrations.AddField(
            model_name='userscheduledata',
            name='commute_pss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userscheduledata',
            name='duration_single_commute_in_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
