# Generated by Django 3.0 on 2020-04-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20200328_0834'),
        ('user_profile', '0009_merge_20200326_1805'),
    ]

    operations = [
    ]
