# Generated by Django 3.0 on 2020-04-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20200330_0016'),
        ('user_profile', '0010_auto_20200328_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='user_auth.UserAuthModel'),
        ),
    ]
