# Generated by Django 3.0 on 2020-04-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20200405_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscheduledata',
            name='commute_pss',
        ),
    ]
