# Generated by Django 3.0 on 2020-04-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_merge_20200403_1001'),
        ('user_profile', '0014_auto_20200408_0707'),
    ]

    operations = [
    ]
