# Generated by Django 3.0 on 2020-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_merge_20200412_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalisedata',
            name='starting_acute_load',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userpersonalisedata',
            name='starting_load',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userpersonalisedata',
            name='starting_prs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userpersonalisedata',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userscheduledata',
            name='duration_single_commute_in_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
