# Generated by Django 3.0 on 2020-05-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_auto_20200509_0957'),
        ('user_profile', '0017_auto_20200513_0848'),
    ]

    operations = [
    ]
