# Generated by Django 3.0 on 2020-05-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_merge_20200520_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalisedata',
            name='profile_variable',
            field=models.CharField(default='POWER', max_length=25),
        ),
    ]
