# Generated by Django 3.0 on 2020-05-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_userpersonalisedata_profile_variable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpersonalisedata',
            name='profile_variable',
        ),
    ]
