# Generated by Django 3.0 on 2020-05-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0020_remove_userpersonalisedata_profile_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalisedata',
            name='is_power_meter_available',
            field=models.BooleanField(default=True),
        ),
    ]
