# Generated by Django 3.0 on 2020-07-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0024_auto_20200708_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UTC', help_text='Name of a timezone.', max_length=55)),
                ('offset', models.CharField(default='+0:00', help_text='Offset of a timezone.', max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timezone Truth Table',
                'db_table': 'timezone',
            },
        ),
    ]
