# Generated by Django 3.0 on 2020-07-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0026_auto_20200710_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timezone',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='updated_at',
        ),
    ]
