# Generated by Django 3.0 on 2020-07-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0027_auto_20200710_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='timezone_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timezone_offset',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.TimeZone'),
        ),
    ]
