# Generated by Django 3.0 on 2020-07-09 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0028_auto_20200710_0214'),
    ]

    operations = [
        migrations.RunSQL("update user_profile set timezone_id = timezone.id  from timezone"
                          " where timezone.type='UTC' and timezone.offset = '+0:00';")
    ]
