# Generated by Django 3.0 on 2020-08-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0031_auto_20200714_0308'),
    ]

    operations = [
        migrations.RunSQL(
            "update user_profile set timezone_id = null where 1=1;"
            "delete from timezone where 1=1;"
        )
    ]
