# Generated by Django 3.0 on 2020-08-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0032_auto_20200803_1839'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (1, 'Hawaii Standard Time', '-10:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (2, 'Alaska Standard Time', '-9:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (3, 'Pacific Standard Time', '-8:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (4, 'Mountain Standard Time', '-7:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (5, 'Central Standard Time', '-6:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (6, 'Eastern Standard Time', '-5:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (7, 'Atlantic Standard Time', '-4:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (8, 'Argentina Time', '-3:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (9, 'Mid-Atlantic Time', '-2:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (10, 'Azores Time', '-1:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (11, 'Greenwich Mean Time', '+0:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (12, 'Central European Time', '+1:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (13, 'Eastern European Time', '+2:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (14, 'Central/South Africa Time', '+2:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (15, 'Arabia Standard Time', '+3:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (16, 'Eastern Africa Time', '+3:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (17, 'Moscow Time', '+3:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (18, 'Armenia Time', '+4:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (19, 'Pakistan Standard Time', '+5:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (20, 'India Standard Time', '+5:30', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (21, 'Omsk Time', '+6:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (22, 'Bangladesh Time', '+6:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (23, 'Kranoyask Time', '+7:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (24, 'China Standard Time', '+8:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (25, 'Australian Western Time', '+8:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (26, 'Japan Standard Time', '+9:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (27, 'Australian Central Time', '+9:30', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (28, 'Australian Eastern Time', '+8:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (29, 'Australian Eastern Time', '+10:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (30, 'Sakhalin Time', '+11:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (31, 'New Zealand Time', '+12:00', True, 'UTC');"
            "INSERT INTO timezone (id, name, \"offset\", is_active, type) VALUES (32, 'Samoa Standard Time', '+13:00', True, 'UTC');"
        )
    ]
