# Generated by Django 3.0 on 2020-08-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0033_auto_20200803_1839'),
    ]

    operations = [
        migrations.RunSQL("update user_profile set timezone_id = timezone.id  from timezone"
                          " where timezone.type='UTC' and timezone.offset = '+0:00';")
    ]
