# Generated by Django 3.0 on 2020-08-04 06:08

import django.db.models.deletion
from django.db import migrations, models

import config.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_merge_20200804_1207'),
        ('user_profile', '0034_auto_20200803_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(storage=config.storage_backends.PrivateMediaStorage(), upload_to='avatars')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'User Profile Image Table',
                'db_table': 'profile_image',
            },
        ),
    ]
