# Generated by Django 3.0 on 2020-08-31 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0039_auto_20200821_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTrainingDurationsInHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day_duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('second_day_duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('third_day_duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('fourth_day_duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('fifth_day_duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('sixth_day_duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('seventh_day_duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Available Training Duration Table',
                'db_table': 'training_duration',
            },
        ),
        migrations.CreateModel(
            name='CommuteWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.BooleanField(default=False)),
                ('second_day', models.BooleanField(default=False)),
                ('third_day', models.BooleanField(default=False)),
                ('fourth_day', models.BooleanField(default=False)),
                ('fifth_day', models.BooleanField(default=False)),
                ('sixth_day', models.BooleanField(default=False)),
                ('seventh_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commute by Bike Day',
                'db_table': 'commute_by_bike_day',
            },
        ),
        migrations.CreateModel(
            name='UserTrainingAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commute_to_work_by_bike', models.BooleanField(default=False)),
                ('duration_single_commute_in_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_training_hours_per_day_outside_commuting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_training_availabilities', to='user_profile.AvailableTrainingDurationsInHour')),
                ('days_commute_by_bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_training_availabilities', to='user_profile.CommuteWeek')),
            ],
            options={
                'verbose_name': 'User Training Availability Table',
                'db_table': 'user_training_availability',
            },
        ),
    ]
