# Generated by Django 3.0 on 2020-09-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0040_auto_20200830_1052'),
        ('user_profile', '0040_auto_20200827_0123'),
    ]

    operations = [
    ]
