# Generated by Django 3.0 on 2020-08-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0040_availabletrainingdurationsinhour_commuteweek_usertrainingavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrainingavailability',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usertrainingavailability',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
