# Generated by Django 3.0 on 2020-08-31 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0016_remove_userauthmodel_training_availability'),
        ('user_profile', '0041_auto_20200831_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrainingavailability',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_availabilities', to='user_auth.UserAuthModel'),
            preserve_default=False,
        ),
    ]
