# Generated by Django 3.0 on 2020-09-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0043_auto_20200901_0833'),
        ('user_profile', '0043_auto_20200907_2303'),
    ]

    operations = [
    ]
