# Generated by Django 3.0 on 2020-10-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0048_auto_20201008_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
