# Generated by Django 3.0 on 2020-10-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0049_userprofile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalisedata',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
