# Generated by Django 3.0 on 2020-10-19 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0020_auto_20201005_1751'),
        ('user_profile', '0050_userpersonalisedata_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpersonalisedata',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userpersonalisedata',
            name='user_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalise_data_temp', to='user_auth.UserAuthModel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_data_temp', to='user_auth.UserAuthModel'),
        ),
    ]
