# Generated by Django 3.0 on 2020-10-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0021_auto_20201019_1708'),
        ('user_profile', '0052_auto_20201019_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalisedata',
            name='user_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalise_data', to='user_auth.UserAuthModel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_data', to='user_auth.UserAuthModel'),
        ),
    ]
