# Generated by Django 3.0 on 2020-10-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0054_auto_20201020_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpersonalisedata',
            options={'ordering': ['id'], 'verbose_name': 'User Personalise Data Table'},
        ),
    ]
