# Generated by Django 3.0 on 2020-10-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0056_auto_20201026_1746'),
        ('user_profile', '0047_auto_20201026_0751'),
    ]

    operations = [
    ]
