# Generated by Django 3.0 on 2020-11-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0058_auto_20201027_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalisedata',
            name='fthr_input_denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpersonalisedata',
            name='ftp_input_denied',
            field=models.BooleanField(default=False),
        ),
    ]
