# Generated by Django 3.0 on 2020-12-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0059_auto_20201209_0741'),
        ('user_profile', '0062_auto_20201205_1744'),
    ]

    operations = [
    ]
