# Generated by Django 3.0 on 2020-12-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0063_merge_20201221_0546'),
        ('user_profile', '0064_auto_20201218_1757'),
    ]

    operations = [
    ]
