# Generated by Django 3.0 on 2020-12-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0064_auto_20201222_0725'),
        ('user_profile', '0066_auto_20201221_0614'),
    ]

    operations = [
    ]
