# Generated by Django 3.0 on 2021-01-19 19:36

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0021_auto_20201019_1708'),
        ('user_profile', '0069_auto_20201230_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('app_version', models.CharField(help_text='User app version', max_length=255)),
                ('hash', models.CharField(help_text='User app version', max_length=255)),
                ('device_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user_auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'User MetaData',
                'db_table': 'user_metadata',
            },
        ),
    ]
