# Generated by Django 3.0 on 2021-01-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0070_usermetadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermetadata',
            old_name='app_version',
            new_name='build_number',
        ),
    ]
