# Generated by Django 3.0 on 2021-05-28 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0021_auto_20201019_1708'),
        ('user_profile', '0073_auto_20210408_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneDifficultyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('zone_three_level', models.SmallIntegerField(default=0)),
                ('zone_four_level', models.SmallIntegerField(default=0)),
                ('zone_five_level', models.SmallIntegerField(default=0)),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_difficulty_levels', to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'Zone Difficulty Level',
                'db_table': 'zone_difficulty_level',
            },
        ),
    ]
