# Generated by Django 3.0 on 2021-06-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0074_zonedifficultylevel'),
        ('user_profile', '0075_auto_20210527_1536'),
    ]

    operations = [
    ]
