# Generated by Django 3.0 on 2021-06-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0077_auto_20210611_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_level',
            field=models.CharField(choices=[('PROFILE', 'Profile'), ('HOME', 'Home')], default='PROFILE', help_text='Defines if the user has completed the onboarding process and can access the home page of the app or not', max_length=25),
        ),
    ]
