# Generated by Django 3.0 on 2021-06-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0079_auto_20210628_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='user',
            new_name='user_auth',
        ),
        migrations.RenameField(
            model_name='usertrainingavailability',
            old_name='user',
            new_name='user_auth',
        ),
    ]
