# Generated by Django 3.2.5 on 2021-09-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0081_auto_20210628_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalisedata',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
