# Generated by Django 3.2.5 on 2021-09-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0084_alter_useractivitylog_activity_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonedifficultylevel',
            name='zone_hc_level',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zonedifficultylevel',
            name='zone_seven_level',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zonedifficultylevel',
            name='zone_six_level',
            field=models.SmallIntegerField(default=0),
        ),
    ]
