# Generated by Django 3.2.5 on 2021-09-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0082_alter_userpersonalisedata_weight'),
        ('user_profile', '0085_auto_20210916_2037'),
    ]

    operations = [
    ]
