# Generated by Django 3.2.5 on 2022-02-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0087_alter_useractivitylog_activity_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpersonalisedata',
            name='user_auth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_auth',
        ),
        migrations.RemoveField(
            model_name='zonedifficultylevel',
            name='user_auth',
        ),
    ]
