# Generated by Django 3.2.5 on 2022-02-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0089_remove_profileimage_user_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermetadata',
            name='user_auth',
        ),
    ]
