# Generated by Django 3.2.5 on 2022-06-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0090_remove_usermetadata_user_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='offset_second',
            field=models.IntegerField(default=0, help_text='Offset in second'),
            preserve_default=False,
        ),
    ]
