# Generated by Django 3.0 on 2020-02-10 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.IntegerField(choices=[(1, 'Sportive'), (2, 'Multi-Day'), (3, 'Time Trial'), (4, 'Criterium'), (5, 'Road Race'), (6, 'Zwift Race'), (7, 'Triathlon'), (8, 'Fitness')])),
                ('event_sub_type', models.CharField(max_length=55)),
                ('distance_type', models.IntegerField(choices=[(1, 'Short'), (2, 'Medium'), (3, 'Long')])),
                ('climbing_ratio', models.IntegerField()),
                ('typical_minimum_distance', models.IntegerField()),
                ('typical_maximum_distance', models.IntegerField()),
                ('typical_minimum_elevation_gain', models.IntegerField()),
                ('typical_maximum_elevation_gain', models.IntegerField()),
                ('complete_ctl', models.IntegerField()),
                ('compete_ctl', models.IntegerField()),
                ('podium_ctl', models.IntegerField()),
                ('complete_approx_weekly_hrs', models.IntegerField()),
                ('compete_approx_weekly_hrs', models.IntegerField()),
                ('podium_approx_weekly_hrs', models.IntegerField()),
                ('is_active', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'verbose_name': 'Event Type Table',
                'db_table': 'event_type',
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=55)),
                ('distance_per_day', models.IntegerField()),
                ('elevation_gain', models.IntegerField()),
                ('event_date', models.DateTimeField()),
                ('performance_goal', models.IntegerField(choices=[(1, 'Complete'), (2, 'Compete'), (3, 'Podium')])),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.UserAuthModel')),
            ],
            options={
                'verbose_name': 'User Event Type Table',
                'db_table': 'user_event',
            },
        ),
        migrations.CreateModel(
            name='NamedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=55)),
                ('distance_per_day', models.IntegerField()),
                ('elevation_gain', models.IntegerField()),
                ('event_date', models.DateTimeField()),
                ('performance_goal', models.IntegerField(choices=[(1, 'Complete'), (2, 'Compete'), (3, 'Podium')])),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventType')),
            ],
            options={
                'verbose_name': 'Named Event Type Table',
                'db_table': 'named_event',
            },
        ),
    ]
