# Generated by Django 3.0 on 2020-02-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='distance_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='elevation_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
