# Generated by Django 3.0 on 2020-02-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200212_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedevent',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.EventType'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.EventType'),
        ),
    ]
