# Generated by Django 3.0 on 2020-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200212_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtype',
            old_name='event_sub_type',
            new_name='sub_type',
        ),
        migrations.RenameField(
            model_name='eventtype',
            old_name='event_type_name',
            new_name='type',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='plan_name',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='climbing_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='compete_approx_weekly_hrs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='compete_ctl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='complete_approx_weekly_hrs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='complete_ctl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='podium_approx_weekly_hrs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='podium_ctl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='typical_maximum_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='typical_maximum_elevation_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='typical_minimum_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='typical_minimum_elevation_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namedevent',
            name='distance_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namedevent',
            name='elevation_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namedevent',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
