# Generated by Django 3.0 on 2020-02-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200212_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='complete_approx_weekly_hrs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='sub_type',
            field=models.CharField(choices=[(1, 'Sportive'), (2, 'Multi-Day'), (3, 'Time Trial'), (4, '10 miles'), (5, '25 miles'), (6, '50+ plus'), (7, '50+ plus'), (8, '50+ plus'), (9, 'Criterium'), (10, 'Road Race'), (11, 'Zwift Race'), (12, 'Triathlon')], max_length=55, null=True),
        ),
    ]
