# Generated by Django 3.0 on 2020-02-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20200218_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='climbing_ratio',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='compete_approx_weekly_hrs',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='compete_ctl',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='complete_approx_weekly_hrs',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='complete_ctl',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='podium_approx_weekly_hrs',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='podium_ctl',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='typical_maximum_distance',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='typical_maximum_elevation_gain',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='typical_minimum_distance',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='typical_minimum_elevation_gain',
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='distance_type',
            field=models.IntegerField(choices=[(1, 'Short'), (2, 'Medium'), (3, 'Long')], null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.IntegerField(choices=[(1, 'Sportive'), (2, 'Multi-Day'), (3, 'Time Trial'), (4, 'Criterium'), (5, 'Road Race'), (6, 'Zwift Race'), (7, 'Triathlon'), (8, 'Fitness')], null=True),
        ),
        migrations.CreateModel(
            name='EventTypeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climbing_ratio', models.IntegerField(blank=True, null=True)),
                ('typical_minimum_distance', models.IntegerField(blank=True, null=True)),
                ('typical_maximum_distance', models.IntegerField(blank=True, null=True)),
                ('typical_minimum_elevation_gain', models.IntegerField(blank=True, null=True)),
                ('typical_maximum_elevation_gain', models.IntegerField(blank=True, null=True)),
                ('complete_ctl', models.IntegerField(blank=True, null=True)),
                ('compete_ctl', models.IntegerField(blank=True, null=True)),
                ('podium_ctl', models.IntegerField(blank=True, null=True)),
                ('complete_approx_weekly_hrs', models.FloatField(blank=True, null=True)),
                ('compete_approx_weekly_hrs', models.FloatField(blank=True, null=True)),
                ('podium_approx_weekly_hrs', models.FloatField(blank=True, null=True)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.EventType')),
            ],
        ),
    ]
