# Generated by Django 3.0 on 2020-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20200221_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtypedetails',
            options={'verbose_name': 'Event Type Details Table'},
        ),
        migrations.RenameField(
            model_name='eventtypedetails',
            old_name='compete_ctl',
            new_name='compete_lower_target_prs',
        ),
        migrations.RenameField(
            model_name='eventtypedetails',
            old_name='complete_ctl',
            new_name='compete_upper_target_prs',
        ),
        migrations.RenameField(
            model_name='eventtypedetails',
            old_name='podium_ctl',
            new_name='complete_lower_target_prs',
        ),
        migrations.RenameField(
            model_name='eventtypedetails',
            old_name='typical_maximum_distance',
            new_name='complete_upper_target_prs',
        ),
        migrations.RenameField(
            model_name='eventtypedetails',
            old_name='typical_maximum_elevation_gain',
            new_name='maximum_distance',
        ),
        migrations.RenameField(
            model_name='eventtypedetails',
            old_name='typical_minimum_distance',
            new_name='maximum_elevation_gain',
        ),
        migrations.RenameField(
            model_name='eventtypedetails',
            old_name='typical_minimum_elevation_gain',
            new_name='minimum_distance',
        ),
        migrations.RemoveField(
            model_name='eventtypedetails',
            name='compete_approx_weekly_hrs',
        ),
        migrations.RemoveField(
            model_name='eventtypedetails',
            name='complete_approx_weekly_hrs',
        ),
        migrations.RemoveField(
            model_name='eventtypedetails',
            name='podium_approx_weekly_hrs',
        ),
        migrations.AddField(
            model_name='eventtypedetails',
            name='minimum_elevation_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtypedetails',
            name='podium_lower_target_prs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtypedetails',
            name='podium_upper_target_prs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='eventtypedetails',
            table='event_type_details',
        ),
    ]
