# Generated by Django 3.0 on 2020-03-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20200326_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedevent',
            name='climbing_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
