# Generated by Django 3.0 on 2020-03-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('event', '0012_auto_20200327_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='user_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='user_auth.UserAuthModel'),
        ),
    ]
