# Generated by Django 3.0 on 2020-03-29 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20200327_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtypedetails',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_type_details', to='event.EventType'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_event_type', to='event.EventType'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='performance_goal',
            field=models.IntegerField(choices=[(1, 'Complete'), (2, 'Compete'), (3, 'Podium')], null=True),
        ),
    ]
