# Generated by Django 3.0 on 2020-03-31 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20200327_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userevent',
            options={'verbose_name': 'User Event Table'},
        ),
    ]
