# Generated by Django 3.0 on 2020-04-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20200330_0016'),
        ('event', '0014_auto_20200331_1849'),
    ]

    operations = [
    ]
