# Generated by Django 3.0 on 2020-04-02 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_merge_20200401_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='event.EventType'),
        ),
    ]
