# Generated by Django 3.0 on 2020-04-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20200402_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='distance_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
