# Generated by Django 3.0 on 2020-04-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_auto_20200408_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtypedetails',
            name='maximum_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtypedetails',
            name='minimum_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
