# Generated by Django 3.0 on 2020-04-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_eventdemandstruthtable_zone0_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtypedetails',
            name='event_type',
        ),
    ]
