# Generated by Django 3.0 on 2020-04-08 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_remove_eventtypedetails_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to='event.EventTypeDetails'),
        ),
    ]
