# Generated by Django 3.0 on 2020-04-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_auto_20200410_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedevent',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='named_event', to='event.EventType'),
        ),
    ]
