# Generated by Django 3.0 on 2020-04-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_auto_20200413_0102'),
        ('event', '0026_auto_20200412_1656'),
    ]

    operations = [
    ]
