# Generated by Django 3.0 on 2020-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_merge_20200413_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtypedetails',
            name='maximum_distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='eventtypedetails',
            name='minimum_distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
