# Generated by Django 3.0 on 2020-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_auto_20200419_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='distance_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
