# Generated by Django 3.0 on 2020-04-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_auto_20200423_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namedevent',
            options={'verbose_name': 'Named Event Table'},
        ),
    ]
