# Generated by Django 3.0 on 2020-05-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_auto_20200424_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='sub_type',
            field=models.IntegerField(choices=[(1, 'Flat'), (2, 'Hilly'), (3, 'Mountains')], null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user_created_event_sub_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Flat'), (2, 'Hilly'), (3, 'Mountains')], null=True),
        ),
    ]
