# Generated by Django 3.0 on 2020-07-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_auto_20200519_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
