# Generated by Django 3.0 on 2020-07-11 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0033_userevent_datetime'),
    ]

    operations = [
        migrations.RunSQL(
            "update user_event set datetime = (cast(date as text) || ' 00:00:00.000000 +00:00')"
            ":: timestamp where id >= 1;")
    ]
