# Generated by Django 3.0 on 2020-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_remove_userevent_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namedevent',
            options={'ordering': ['id'], 'verbose_name': 'Named Event Table'},
        ),
        migrations.AlterField(
            model_name='namedevent',
            name='distance_per_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distance'),
        ),
        migrations.AlterField(
            model_name='namedevent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
