# Generated by Django 3.0 on 2020-09-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_auto_20200912_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevent',
            old_name='datetime',
            new_name='event_date',
        ),
    ]
