# Generated by Django 3.0 on 2021-03-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_auto_20200928_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='sub_type',
            field=models.IntegerField(choices=[(1, 'Flat'), (2, 'Hilly'), (3, 'Mountain')], null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user_created_event_sub_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Flat'), (2, 'Hilly'), (3, 'Mountain')], null=True),
        ),
    ]
