# Generated by Django 3.0 on 2021-01-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_auto_20200928_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedevent',
            name='sports_type',
            field=models.CharField(choices=[('CYCLING', 'CYCLING')], default='CYCLING', help_text='Refers to the type of sports of the event (e.g. Running, Cycling)', max_length=55),
        ),
        migrations.AddField(
            model_name='userevent',
            name='sports_type',
            field=models.CharField(choices=[('CYCLING', 'CYCLING')], default='CYCLING', help_text='Refers to the type of sports of the event (e.g. Running, Cycling)', max_length=55),
        ),
    ]
