# Generated by Django 3.0 on 2021-03-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_auto_20210310_0935'),
        ('event', '0038_auto_20210119_1125'),
    ]

    operations = [
    ]
