# Generated by Django 3.0 on 2021-05-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_auto_20210508_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedevent',
            name='country',
            field=models.CharField(blank=True, help_text='Country where the events happening', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='namedevent',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the Named Event', null=True),
        ),
        migrations.AddField(
            model_name='namedevent',
            name='organiser',
            field=models.CharField(blank=True, help_text='Organiser of the Event', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='namedevent',
            name='postcode',
            field=models.CharField(blank=True, help_text='Postcode of the country', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='namedevent',
            name='sub_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='namedevent',
            name='website_url',
            field=models.CharField(blank=True, help_text='Website link of the event', max_length=5000, null=True),
        ),
    ]
