# Generated by Django 3.0 on 2021-06-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0041_auto_20210518_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedevent',
            name='image_url',
            field=models.CharField(blank=True, help_text='S3 link of the event image', max_length=5000, null=True),
        ),
    ]
