# Generated by Django 3.0 on 2021-06-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0042_namedevent_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedevent',
            name='city',
            field=models.CharField(help_text='City where the event will take place', max_length=255, null=True),
        ),
    ]
