# Generated by Django 3.0 on 2021-06-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0043_namedevent_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedevent',
            name='share_link',
            field=models.TextField(blank=True, help_text='Event share url', null=True),
        ),
    ]
