# Generated by Django 3.0 on 2021-06-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0044_userevent_user_id'),
        ('event', '0044_namedevent_share_link'),
    ]

    operations = [
    ]
