# Generated by Django 3.0 on 2021-07-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0045_merge_20210629_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='named_event_id',
            field=models.IntegerField(help_text='ID of the named event if a predefined event is selected', null=True),
        ),
    ]
