# Generated by Django 3.2.5 on 2022-01-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0046_userevent_named_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedevent',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='namedevent',
            old_name='event_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='namedevent',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.IntegerField(choices=[(1, 'Sportive'), (2, 'Multi-Day')], null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user_created_event_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Sportive'), (2, 'Multi-Day')], null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='userevent',
            old_name='event_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='userevent',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]

