# Generated by Django 3.2.5 on 2022-01-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0048_auto_20220113_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.IntegerField(choices=[(1, 'Sportive'), (2, 'Multi Day')], null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user_created_event_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Sportive'), (2, 'Multi Day')], null=True),
        ),
    ]
